import { FormDataDefinition } from '@/types/form';

/**
 * Premiums / Contribution Strategy
 * Fillout template ID: jgaiJJZJvjus
 * Published URL: https://betafits.fillout.com/t/jgaiJJZJvjus
 *
 * AUTO-GENERATED by scripts/fetch-fillout-published-structure.ts on 2026-04-17T16:17:23.358Z.
 * Do not edit by hand — regenerate instead so the multi-page wizard layout
 * stays in sync with Fillout.
 */
export const FORM_DATA: FormDataDefinition = {
    id: "jgaiJJZJvjus",
    title: "Premiums / Contribution Strategy",
    pages: [
        {
            id: "rKiL",
            name: "Page",
            sections: [
                {
                    id: "rKiL-s0",
                    title: "Page",
                    questions: [
                        {
                            id: "gsvX",
                            label: "Type your question here",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "pc64",
                            label: "Please add or update premiums for each of your plans.",
                            type: "text",
                            required: false,
                        },
                    ],
                }
            ],
        }
    ],
};
