import { FormDataDefinition } from '@/types/form';

/**
 * Compliance
 * Fillout template ID: ujTSx72pr5us
 * Published URL: https://betafits.fillout.com/t/ujTSx72pr5us
 *
 * AUTO-GENERATED by scripts/fetch-fillout-published-structure.ts on 2026-04-17T20:57:12.148Z.
 * Do not edit by hand — regenerate instead so the multi-page wizard layout
 * stays in sync with Fillout.
 */
export const FORM_DATA: FormDataDefinition = {
    id: "ujTSx72pr5us",
    title: "Compliance",
    pages: [
        {
            id: "wVF9-s1-r72b",
            name: "Compliance Overview",
            sections: [
                {
                    id: "wVF9-s1-r72b-s0",
                    title: "Compliance Overview",
                    questions: [
                        {
                            id: "fpKM",
                            label: "How would you describe the level of compliance support you currently receive from your broker or vendors?",
                            type: "checkbox",
                            required: false,
                            options: [
                                { value: "Consistent, proactive guidance on all major compliance areas", label: "Consistent, proactive guidance on all major compliance areas" },
                                { value: "Occasional updates or reminders, mainly during open enrollment", label: "Occasional updates or reminders, mainly during open enrollment" },
                                { value: "Minimal involvement — we manage most compliance tasks internally", label: "Minimal involvement — we manage most compliance tasks internally" },
                                { value: "No broker/vendor involved in compliance", label: "No broker/vendor involved in compliance" },
                                { value: "Not sure", label: "Not sure" },
                            ],
                        },
                        {
                            id: "svnT",
                            label: "What systems or methods are used to track your compliance-related tasks throughout the year?",
                            type: "checkbox",
                            required: false,
                            options: [
                                { value: "HRIS or payroll platform", label: "HRIS or payroll platform" },
                                { value: "Compliance software", label: "Compliance software" },
                                { value: "Broker- or vendor-provided calendar or checklist", label: "Broker- or vendor-provided calendar or checklist" },
                                { value: "Internal spreadsheet or task list", label: "Internal spreadsheet or task list" },
                                { value: "No formal system", label: "No formal system" },
                                { value: "Not sure", label: "Not sure" },
                            ],
                        },
                        {
                            id: "wVUD",
                            label: "What are your primary sources for staying informed about benefits compliance requirements?",
                            type: "checkbox",
                            required: false,
                            options: [
                                { value: "Compliance calendar from broker or Third-Party Administrator", label: "Compliance calendar from broker or Third-Party Administrator" },
                                { value: "Email alerts from broker or carriers", label: "Email alerts from broker or carriers" },
                                { value: "Industry newsletters or webinars", label: "Industry newsletters or webinars" },
                                { value: "Web searches or generative AI tools", label: "Web searches or generative AI tools" },
                                { value: "Internal HR/legal staff", label: "Internal HR/legal staff" },
                                { value: "Not sure", label: "Not sure" },
                            ],
                        },
                    ],
                }
            ],
        },
        {
            id: "wFT2-s1-uz5M",
            name: "Compliance Filing & Document Management",
            sections: [
                {
                    id: "wFT2-s1-uz5M-s0",
                    title: "Compliance Filing & Document Management",
                    questions: [
                        {
                            id: "dc3Q",
                            label: "Who manages your ERISA Wrap Document and ensures it is updated?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Internal HR or legal team", label: "Internal HR or legal team" },
                                { value: "Broker", label: "Broker" },
                                { value: "Third-Party Administrator", label: "Third-Party Administrator" },
                                { value: "We don't have an ERISA Wrap Document", label: "We don't have an ERISA Wrap Document" },
                                { value: "Not sure", label: "Not sure" },
                            ],
                        },
                        {
                            id: "1nxi",
                            label: "How is your Section 125 (Premium Only Plan) Document prepared and kept current?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Internal HR", label: "Internal HR" },
                                { value: "Payroll vendor", label: "Payroll vendor" },
                                { value: "Broker or Third-Party Administrator", label: "Broker or Third-Party Administrator" },
                                { value: "We don't have one", label: "We don't have one" },
                                { value: "Not sure", label: "Not sure" },
                            ],
                        },
                        {
                            id: "9MSF",
                            label: "How is your Health & Welfare Form 5500 prepared and filed?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Broker provides draft of 5500 for signature", label: "Broker provides draft of 5500 for signature" },
                                { value: "Broker helps gather Schedule As and provides guidance", label: "Broker helps gather Schedule As and provides guidance" },
                                { value: "Third-Party Administrator prepares the 5500 and coordinates filing", label: "Third-Party Administrator prepares the 5500 and coordinates filing" },
                                { value: "Payroll vendor or compliance partner provides 5500 support", label: "Payroll vendor or compliance partner provides 5500 support" },
                                { value: "Internal HR or legal team prepares and files directly", label: "Internal HR or legal team prepares and files directly" },
                                { value: "We are not required to file Form 5500", label: "We are not required to file Form 5500" },
                                { value: "Not Sure", label: "Not Sure" },
                            ],
                        },
                    ],
                }
            ],
        },
        {
            id: "fnR8-s1-v5om",
            name: "ACA Compliance Responsibilities",
            sections: [
                {
                    id: "fnR8-s1-v5om-s0",
                    title: "ACA Compliance Responsibilities",
                    questions: [
                        {
                            id: "vHX9",
                            label: "Who prepares and files your ACA Forms 1094/1095?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Payroll vendor", label: "Payroll vendor" },
                                { value: "ACA-specific vendor", label: "ACA-specific vendor" },
                                { value: "Broker or TPA", label: "Broker or TPA" },
                                { value: "Carrier", label: "Carrier" },
                                { value: "Internal HR", label: "Internal HR" },
                                { value: "We are not required to file", label: "We are not required to file" },
                                { value: "Not sure", label: "Not sure" },
                            ],
                        },
                        {
                            id: "1J9u",
                            label: "Is the cost of employer-sponsored healthcare coverage reported on employees W-2s (Box 12 DD)?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Yes, automatically through our payroll system", label: "Yes, automatically through our payroll system" },
                                { value: "Yes, we handle this manually in-house", label: "Yes, we handle this manually in-house" },
                                { value: "No, we do not report this", label: "No, we do not report this" },
                                { value: "Not Sure", label: "Not Sure" },
                            ],
                        },
                    ],
                }
            ],
        },
        {
            id: "fnR8-s2-65RU",
            name: "Compliance Testing & Employee Communication",
            sections: [
                {
                    id: "fnR8-s2-65RU-s0",
                    title: "Compliance Testing & Employee Communication",
                    questions: [
                        {
                            id: "4K16",
                            label: "How are required annual notices delivered to employees?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Included in new hire packets and open enrollment materials", label: "Included in new hire packets and open enrollment materials" },
                                { value: "Sent via email annually to all benefits-eligible employees", label: "Sent via email annually to all benefits-eligible employees" },
                                { value: "Mailed by broker,Third-Party Administrator , or carrier", label: "Mailed by broker,Third-Party Administrator , or carrier" },
                                { value: "Delivered through employee self-service portal or HRIS", label: "Delivered through employee self-service portal or HRIS" },
                                { value: "Unsure how or if these notices are distributed", label: "Unsure how or if these notices are distributed" },
                                { value: "Not Sure", label: "Not Sure" },
                            ],
                        },
                        {
                            id: "6vNE",
                            label: "Do you conduct annual non-discrimination testing for your Health & Welfare plans?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Yes", label: "Yes" },
                                { value: "No", label: "No" },
                                { value: "Not sure", label: "Not sure" },
                            ],
                        },
                        {
                            id: "fMAe",
                            label: "How is annual non-discrimination testing for your Health & Welfare plans handled?",
                            type: "checkbox",
                            required: false,
                            options: [
                                { value: "Internal HR", label: "Internal HR" },
                                { value: "Payroll vendor", label: "Payroll vendor" },
                                { value: "Broker", label: "Broker" },
                                { value: "TPA or benefits consultant", label: "TPA or benefits consultant" },
                                { value: "CPA or accounting firm", label: "CPA or accounting firm" },
                            ],
                        },
                    ],
                }
            ],
        },
        {
            id: "pQqp-s1-51o2",
            name: "Additional Regulatory Filings",
            sections: [
                {
                    id: "pQqp-s1-51o2-s0",
                    title: "Additional Regulatory Filings",
                    questions: [
                        {
                            id: "7eM6",
                            label: "How are the following compliance requirements currently handled?",
                            type: "matrix",
                            required: false,
                            options: [
                                { value: "Handled by Broker", label: "Handled by Broker" },
                                { value: "Managed by Payroll Vendor", label: "Managed by Payroll Vendor" },
                                { value: "Compliance or ACA Vendor", label: "Compliance or ACA Vendor" },
                                { value: "Internal HR or Legal", label: "Internal HR or Legal" },
                                { value: "Not Sure", label: "Not Sure" },
                            ],
                            rows: [
                                { id: "mbNe", label: "1095-B Reporting" },
                                { id: "hTTa", label: "PCORI Filing" },
                                { id: "tcDK", label: "RxDC Reporting" },
                                { id: "uVBo", label: "State-Mandated Benefits Reporting" },
                            ],
                        },
                    ],
                }
            ],
        },
        {
            id: "pQqp-s2-sbhf",
            name: "Leave Management",
            sections: [
                {
                    id: "pQqp-s2-sbhf-s0",
                    title: "Leave Management",
                    questions: [
                        {
                            id: "vZ8p",
                            label: "How do you manage compliance with Paid Leave and other employment-related laws across multiple states?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Dedicated internal team tracks state-specific rules", label: "Dedicated internal team tracks state-specific rules" },
                                { value: "We rely on our broker or compliance vendor to alert us", label: "We rely on our broker or compliance vendor to alert us" },
                                { value: "Payroll/HRIS system provides multi-state compliance support", label: "Payroll/HRIS system provides multi-state compliance support" },
                                { value: "We handle issues reactively, as they come up", label: "We handle issues reactively, as they come up" },
                                { value: "Not sure", label: "Not sure" },
                            ],
                        },
                        {
                            id: "nbY1",
                            label: "What systems or partners help you track and administer leave laws?",
                            type: "checkbox",
                            required: false,
                            options: [
                                { value: "Internal HR tracking (manual or spreadsheet)", label: "Internal HR tracking (manual or spreadsheet)" },
                                { value: "HRIS or leave management module", label: "HRIS or leave management module" },
                                { value: "Insurance carrier or disability vendor", label: "Insurance carrier or disability vendor" },
                                { value: "Third-party leave administrator (TPA)", label: "Third-party leave administrator (TPA)" },
                                { value: "Broker assists with guidance", label: "Broker assists with guidance" },
                                { value: "No structured tracking process in place", label: "No structured tracking process in place" },
                                { value: "Not sure", label: "Not sure" },
                            ],
                        },
                    ],
                }
            ],
        }
    ],
};
