import { FormDataDefinition } from '@/types/form';

/**
 * Broker Role 
 * Fillout template ID: urHF8xDu7eus
 * Published URL: https://betafits.fillout.com/t/urHF8xDu7eus
 *
 * AUTO-GENERATED by scripts/fetch-fillout-published-structure.ts on 2026-04-17T16:01:44.604Z.
 * Do not edit by hand — regenerate instead so the multi-page wizard layout
 * stays in sync with Fillout.
 */
export const FORM_DATA: FormDataDefinition = {
    id: "urHF8xDu7eus",
    title: "Broker Role ",
    pages: [
        {
            id: "nZ7dDkXjzR",
            name: "Page 1",
            sections: [
                {
                    id: "nZ7dDkXjzR-s1-vdyg",
                    title: "General Broker Info",
                    questions: [
                        {
                            id: "iuLc",
                            label: "What type of broker, platform, or consultant supports your employee benefits?",
                            type: "radio",
                            required: false,
                        },
                    ],
                },
                {
                    id: "nZ7dDkXjzR-s2-ehMu",
                    title: "Agreements and Compensation",
                    questions: [
                        {
                            id: "q7SL",
                            label: "Do you have a signed service agreement or only a Broker of Record (BOR) letter?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "1BQA",
                            label: "Do you pay your broker any fees beyond commissions or standard premiums?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "kFtK",
                            label: "Does your broker currently pay for or subsidize any of the following services?",
                            type: "checkbox",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "wF1g",
            name: "Page 2",
            sections: [
                {
                    id: "wF1g-s1-azu1",
                    title: "Communication & Admin Support",
                    questions: [
                        {
                            id: "ucXn",
                            label: "How often do you contact your broker for support?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "oXHq",
                            label: "How often do you have strategic or renewal meetings with your broker?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "17Hj",
                            label: "Which of the following services does your broker currently provide?",
                            type: "checkbox",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "siK1",
            name: "Page 3",
            sections: [
                {
                    id: "siK1-s1-shWv",
                    title: "Broker Evaluation & Satisfaction",
                    questions: [
                        {
                            id: "4vRz",
                            label: "How would you rate your broker’s responsiveness and communication?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "1", label: "1" },
                                { value: "2", label: "2" },
                                { value: "3", label: "3" },
                                { value: "4", label: "4" },
                                { value: "5", label: "5" },
                                { value: "6", label: "6" },
                                { value: "7", label: "7" },
                                { value: "8", label: "8" },
                                { value: "9", label: "9" },
                                { value: "10", label: "10" },
                            ],
                        },
                        {
                            id: "9Xgb",
                            label: "How would you rate your broker’s renewal strategy and plan benchmarking?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "1", label: "1" },
                                { value: "2", label: "2" },
                                { value: "3", label: "3" },
                                { value: "4", label: "4" },
                                { value: "5", label: "5" },
                                { value: "6", label: "6" },
                                { value: "7", label: "7" },
                                { value: "8", label: "8" },
                                { value: "9", label: "9" },
                                { value: "10", label: "10" },
                            ],
                        },
                        {
                            id: "mDVP",
                            label: "How would you rate your broker’s compliance and documentation support?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "1", label: "1" },
                                { value: "2", label: "2" },
                                { value: "3", label: "3" },
                                { value: "4", label: "4" },
                                { value: "5", label: "5" },
                                { value: "6", label: "6" },
                                { value: "7", label: "7" },
                                { value: "8", label: "8" },
                                { value: "9", label: "9" },
                                { value: "10", label: "10" },
                            ],
                        },
                        {
                            id: "6aHN",
                            label: "How would you rate your broker’s admin coordination and day-to-day support?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "1", label: "1" },
                                { value: "2", label: "2" },
                                { value: "3", label: "3" },
                                { value: "4", label: "4" },
                                { value: "5", label: "5" },
                                { value: "6", label: "6" },
                                { value: "7", label: "7" },
                                { value: "8", label: "8" },
                                { value: "9", label: "9" },
                                { value: "10", label: "10" },
                            ],
                        },
                        {
                            id: "1YiE",
                            label: "How would you rate your broker’s value as a strategic partner?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "1", label: "1" },
                                { value: "2", label: "2" },
                                { value: "3", label: "3" },
                                { value: "4", label: "4" },
                                { value: "5", label: "5" },
                                { value: "6", label: "6" },
                                { value: "7", label: "7" },
                                { value: "8", label: "8" },
                                { value: "9", label: "9" },
                                { value: "10", label: "10" },
                            ],
                        },
                        {
                            id: "aJXW",
                            label: "Please upload any broker documentation you have (e.g., signed service agreement or CAA compensation disclosure).",
                            type: "file",
                            required: false,
                        },
                    ],
                }
            ],
        }
    ],
};
