import { FormDataDefinition } from '@/types/form';

/**
 * New Group Form
 * Fillout template ID: xn4WCJ9D8pus
 * Published URL: https://betafits.fillout.com/t/xn4WCJ9D8pus
 *
 * AUTO-GENERATED by scripts/fetch-fillout-published-structure.ts on 2026-04-17T16:01:37.761Z.
 * Do not edit by hand — regenerate instead so the multi-page wizard layout
 * stays in sync with Fillout.
 */
export const FORM_DATA: FormDataDefinition = {
    id: "xn4WCJ9D8pus",
    title: "New Group Form",
    pages: [
        {
            id: "iBNU",
            name: "Page",
            sections: [
                {
                    id: "iBNU-s0",
                    title: "Page",
                    questions: [
                        {
                            id: "vATB",
                            label: "Company Name",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "2uHd",
                            label: "Link to Users",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "jf4z",
                            label: "Link to Assigned Forms",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "rT74",
                            label: "Document Type",
                            type: "select",
                            required: false,
                        },
                        {
                            id: "vr6K",
                            label: "Upload New Group Document",
                            type: "file",
                            required: false,
                        },
                        {
                            id: "ewYV",
                            label: "Upload Group's Document",
                            type: "text",
                            required: false,
                        },
                    ],
                }
            ],
        }
    ],
};
