import { FormDataDefinition } from '@/types/form';

/**
 * Benefits Pulse Survey
 * Fillout template ID: eQ7FVU76PDus
 * Published URL: https://betafits.fillout.com/t/eQ7FVU76PDus
 *
 * AUTO-GENERATED by scripts/fetch-fillout-published-structure.ts on 2026-04-17T17:07:11.088Z.
 * Do not edit by hand — regenerate instead so the multi-page wizard layout
 * stays in sync with Fillout.
 */
export const FORM_DATA: FormDataDefinition = {
    id: "eQ7FVU76PDus",
    title: "Benefits Pulse Survey",
    pages: [
        {
            id: "gas4yyqPYF",
            name: "Page",
            sections: [
                {
                    id: "gas4yyqPYF-s0",
                    title: "Page",
                    questions: [
                        {
                            id: "kGqMobiUDPcHQXPEsEWGhs",
                            label: "Company",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "bNkoRCS16B1NF8Vu3Kz9JR",
                            label: "Benefit Year",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "2023", label: "2023" },
                                { value: "2024", label: "2024" },
                                { value: "2025", label: "2025" },
                            ],
                        },
                        {
                            id: "9xm1AdHoV7ZErSGuemYwT3",
                            label: "How are you currently enrolled for health benefits?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Employee Only", label: "Employee Only" },
                                { value: "Employee + Spouse", label: "Employee + Spouse" },
                                { value: "Employee + Child(ren)", label: "Employee + Child(ren)" },
                                { value: "Family", label: "Family" },
                                { value: "Waived", label: "Waived" },
                                { value: "Not Eligible", label: "Not Eligible" },
                            ],
                        },
                        {
                            id: "9rvPU3rfdvaY6355Si6DTP",
                            label: "On which medical plan are you enrolled?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Option 1", label: "Option 1" },
                                { value: "Option 2", label: "Option 2" },
                            ],
                        },
                        {
                            id: "1tTsT4b7YxSrc2e8bTQtMD",
                            label: "Overall Benefits Package",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "1", label: "1" },
                                { value: "2", label: "2" },
                                { value: "3", label: "3" },
                                { value: "4", label: "4" },
                                { value: "5", label: "5" },
                                { value: "6", label: "6" },
                                { value: "7", label: "7" },
                                { value: "8", label: "8" },
                                { value: "9", label: "9" },
                                { value: "10", label: "10" },
                            ],
                        },
                        {
                            id: "eVZknTJzZyJ8XMoKqUeVFW",
                            label: "Medical Plan Options",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "1", label: "1" },
                                { value: "2", label: "2" },
                                { value: "3", label: "3" },
                                { value: "4", label: "4" },
                                { value: "5", label: "5" },
                                { value: "6", label: "6" },
                                { value: "7", label: "7" },
                                { value: "8", label: "8" },
                                { value: "9", label: "9" },
                                { value: "10", label: "10" },
                            ],
                        },
                        {
                            id: "4UCLbaHFiRB9ARDkPVvqDd",
                            label: "Medical Network",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "1", label: "1" },
                                { value: "2", label: "2" },
                                { value: "3", label: "3" },
                                { value: "4", label: "4" },
                                { value: "5", label: "5" },
                                { value: "6", label: "6" },
                                { value: "7", label: "7" },
                                { value: "8", label: "8" },
                                { value: "9", label: "9" },
                                { value: "10", label: "10" },
                            ],
                        },
                        {
                            id: "gEoRfJNxN37JVkvyow4NWU",
                            label: "Employee Costs",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "1", label: "1" },
                                { value: "2", label: "2" },
                                { value: "3", label: "3" },
                                { value: "4", label: "4" },
                                { value: "5", label: "5" },
                                { value: "6", label: "6" },
                                { value: "7", label: "7" },
                                { value: "8", label: "8" },
                                { value: "9", label: "9" },
                                { value: "10", label: "10" },
                            ],
                        },
                        {
                            id: "qgw9BnxZsRS2b3oc5iH5ej",
                            label: "Other Benefits (Non-Medical)",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "1", label: "1" },
                                { value: "2", label: "2" },
                                { value: "3", label: "3" },
                                { value: "4", label: "4" },
                                { value: "5", label: "5" },
                                { value: "6", label: "6" },
                                { value: "7", label: "7" },
                                { value: "8", label: "8" },
                                { value: "9", label: "9" },
                                { value: "10", label: "10" },
                            ],
                        },
                        {
                            id: "6EbFGLKbaNEhDbn4FyCD2J",
                            label: "Comments",
                            type: "textarea",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "2TMD",
            name: "Page 2",
            sections: [
                {
                    id: "2TMD-s0",
                    title: "Page 2",
                    questions: [
                        {
                            id: "8w6e",
                            label: "Type your question here",
                            type: "text",
                            required: false,
                        },
                    ],
                }
            ],
        }
    ],
};
