import { FormDataDefinition } from '@/types/form';

/**
 * Compliance
 * Fillout template ID: ujTSx72pr5us
 * Published URL: https://betafits.fillout.com/t/ujTSx72pr5us
 *
 * AUTO-GENERATED by scripts/fetch-fillout-published-structure.ts on 2026-04-17T16:01:38.822Z.
 * Do not edit by hand — regenerate instead so the multi-page wizard layout
 * stays in sync with Fillout.
 */
export const FORM_DATA: FormDataDefinition = {
    id: "ujTSx72pr5us",
    title: "Compliance",
    pages: [
        {
            id: "wVF9",
            name: "Page 1",
            sections: [
                {
                    id: "wVF9-s1-r72b",
                    title: "Compliance Overview",
                    questions: [
                        {
                            id: "fpKM",
                            label: "How would you describe the level of compliance support you currently receive from your broker or vendors?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "svnT",
                            label: "What systems or methods are used to track your compliance-related tasks throughout the year?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "wVUD",
                            label: "What are your primary sources for staying informed about benefits compliance requirements?",
                            type: "checkbox",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "wFT2",
            name: "page 2",
            sections: [
                {
                    id: "wFT2-s1-uz5M",
                    title: "Compliance Filing & Document Management",
                    questions: [
                        {
                            id: "dc3Q",
                            label: "Who manages your ERISA Wrap Document and ensures it is updated?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "1nxi",
                            label: "How is your Section 125 (Premium Only Plan) Document prepared and kept current?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "9MSF",
                            label: "How is your Health & Welfare Form 5500 prepared and filed?",
                            type: "radio",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "fnR8",
            name: "Page 3",
            sections: [
                {
                    id: "fnR8-s1-v5om",
                    title: "ACA Compliance Responsibilities",
                    questions: [
                        {
                            id: "vHX9",
                            label: "Who prepares and files your ACA Forms 1094/1095?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "1J9u",
                            label: "Is the cost of employer-sponsored healthcare coverage reported on employees W-2s (Box 12 DD)?",
                            type: "radio",
                            required: false,
                        },
                    ],
                },
                {
                    id: "fnR8-s2-65RU",
                    title: "Compliance Testing & Employee Communication",
                    questions: [
                        {
                            id: "4K16",
                            label: "How are required annual notices delivered to employees?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "6vNE",
                            label: "Do you conduct annual non-discrimination testing for your Health & Welfare plans?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "fMAe",
                            label: "How is annual non-discrimination testing for your Health & Welfare plans handled?",
                            type: "checkbox",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "pQqp",
            name: "Page 4",
            sections: [
                {
                    id: "pQqp-s1-51o2",
                    title: "Additional Regulatory Filings",
                    questions: [
                        {
                            id: "7eM6",
                            label: "How are the following compliance requirements currently handled?",
                            type: "text",
                            required: false,
                        },
                    ],
                },
                {
                    id: "pQqp-s2-sbhf",
                    title: "Leave Management",
                    questions: [
                        {
                            id: "vZ8p",
                            label: "How do you manage compliance with Paid Leave and other employment-related laws across multiple states?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "nbY1",
                            label: "What systems or partners help you track and administer leave laws?",
                            type: "checkbox",
                            required: false,
                        },
                    ],
                }
            ],
        }
    ],
};
