import { FormDataDefinition } from '@/types/form';

/**
 * Benefits Administration
 * Fillout template ID: fYJ3MNj7VQus
 * Published URL: https://betafits.fillout.com/t/fYJ3MNj7VQus
 *
 * AUTO-GENERATED by scripts/fetch-fillout-published-structure.ts on 2026-04-17T17:07:07.091Z.
 * Do not edit by hand — regenerate instead so the multi-page wizard layout
 * stays in sync with Fillout.
 */
export const FORM_DATA: FormDataDefinition = {
    id: "fYJ3MNj7VQus",
    title: "Benefits Administration",
    pages: [
        {
            id: "4pSAP3RVqR-s1-eepx",
            name: "Carrier & Payroll Processes",
            sections: [
                {
                    id: "4pSAP3RVqR-s1-eepx-s0",
                    title: "Carrier & Payroll Processes",
                    questions: [
                        {
                            id: "pmLe",
                            label: "How are benefit carrier updates managed and who is responsible for submitting them?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Internal HR/benefits team via HR/payroll system", label: "Internal HR/benefits team via HR/payroll system" },
                                { value: "Internal HR directly with carrier", label: "Internal HR directly with carrier" },
                                { value: "External broker handles updates", label: "External broker handles updates" },
                                { value: "Payroll vendor handles updates", label: "Payroll vendor handles updates" },
                                { value: "Integrated with HR/payroll/ben admin system", label: "Integrated with HR/payroll/ben admin system" },
                                { value: "Other", label: "Other" },
                            ],
                        },
                        {
                            id: "gT66",
                            label: "Please specify",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "sYyR",
                            label: "How are payroll deduction changes managed and who is responsible for completing them?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Internal HR/benefits team via HR/payroll system", label: "Internal HR/benefits team via HR/payroll system" },
                                { value: "Internal HR directly with carrier", label: "Internal HR directly with carrier" },
                                { value: "External broker handles updat", label: "External broker handles updat" },
                                { value: "Payroll vendor handles updates", label: "Payroll vendor handles updates" },
                                { value: "Integrated with HR/payroll/ben admin system", label: "Integrated with HR/payroll/ben admin system" },
                                { value: "Other", label: "Other" },
                            ],
                        },
                        {
                            id: "313V",
                            label: "Please specify",
                            type: "text",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "4pSAP3RVqR-s2-uKk2",
            name: "Enrollment & Deduction Audits",
            sections: [
                {
                    id: "4pSAP3RVqR-s2-uKk2-s0",
                    title: "Enrollment & Deduction Audits",
                    questions: [
                        {
                            id: "4vFw",
                            label: "How do you perform enrollment and deduction audits (e.g., confirming employees are properly enrolled and deductions are accurate)?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Manually cross-check enrollment and payroll reports", label: "Manually cross-check enrollment and payroll reports" },
                                { value: "Use HR/benefits platform audit tools", label: "Use HR/benefits platform audit tools" },
                                { value: "Audits performed by broker or vendor", label: "Audits performed by broker or vendor" },
                                { value: "Automated via integrated platform", label: "Automated via integrated platform" },
                                { value: "No formal process", label: "No formal process" },
                                { value: "Other", label: "Other" },
                            ],
                        },
                        {
                            id: "iPzP",
                            label: "Please specify",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "s5oB",
                            label: "How frequently do you audit enrollments?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Monthly", label: "Monthly" },
                                { value: "Quarterly", label: "Quarterly" },
                                { value: "Primarily after Open Enrollment", label: "Primarily after Open Enrollment" },
                                { value: "Only as needed", label: "Only as needed" },
                                { value: "Not sure", label: "Not sure" },
                            ],
                        },
                        {
                            id: "nSQt",
                            label: "How frequently do you audit payroll deductions?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Per paycheck", label: "Per paycheck" },
                                { value: "Monthly", label: "Monthly" },
                                { value: "Quarterly", label: "Quarterly" },
                                { value: "Primarily after Open Enrollment", label: "Primarily after Open Enrollment" },
                                { value: "Only as needed", label: "Only as needed" },
                                { value: "Not sure", label: "Not sure" },
                            ],
                        },
                    ],
                }
            ],
        },
        {
            id: "bhvo-s1-pWVs",
            name: "New Hire Benefits Communication",
            sections: [
                {
                    id: "bhvo-s1-pWVs-s0",
                    title: "New Hire Benefits Communication",
                    questions: [
                        {
                            id: "qMuK",
                            label: "How is your benefits guide shared with employees?",
                            type: "checkbox",
                            required: false,
                            options: [
                                { value: "PDF (sent via email or shared drive)", label: "PDF (sent via email or shared drive)" },
                                { value: "Internal intranet page or microsite", label: "Internal intranet page or microsite" },
                                { value: "Company’s public website", label: "Company’s public website" },
                                { value: "Printed handout or booklet", label: "Printed handout or booklet" },
                                { value: "Slides", label: "Slides" },
                                { value: "We do not provide a formal guide", label: "We do not provide a formal guide" },
                            ],
                        },
                        {
                            id: "46Ef",
                            label: "Who creates or updates your benefit guide?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Primarily the internal HR or benefits team", label: "Primarily the internal HR or benefits team" },
                                { value: "Primarily Broker", label: "Primarily Broker" },
                                { value: "Collaboration between HR team and broker", label: "Collaboration between HR team and broker" },
                                { value: "We use carrier-provided materials only (no custom guide)", label: "We use carrier-provided materials only (no custom guide)" },
                                { value: "We don’t provide a benefits guide", label: "We don’t provide a benefits guide" },
                                { value: "Other", label: "Other" },
                            ],
                        },
                        {
                            id: "bgfx",
                            label: "Please specify",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "fNU6",
                            label: "What type of email communication is sent to new hires about their benefits?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Automatically sent through HR/onboarding system", label: "Automatically sent through HR/onboarding system" },
                                { value: "Manually sent by internal HR", label: "Manually sent by internal HR" },
                                { value: "Sent by external broker", label: "Sent by external broker" },
                                { value: "No consistent communication sent", label: "No consistent communication sent" },
                            ],
                        },
                        {
                            id: "5BXX",
                            label: "When are benefits instructions typically sent to new hires?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Before the employee’s first day", label: "Before the employee’s first day" },
                                { value: "During their first week", label: "During their first week" },
                                { value: "After benefits eligibility is reached", label: "After benefits eligibility is reached" },
                                { value: "We do not send benefits instructions", label: "We do not send benefits instructions" },
                            ],
                        },
                    ],
                }
            ],
        },
        {
            id: "bhvo-s2-iEt4",
            name: "Orientation & Support",
            sections: [
                {
                    id: "bhvo-s2-iEt4-s0",
                    title: "Orientation & Support",
                    questions: [
                        {
                            id: "pdzn",
                            label: "How do you deliver benefits orientation to new hires?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "1:1 orientation sessions", label: "1:1 orientation sessions" },
                                { value: "Group orientation sessions", label: "Group orientation sessions" },
                                { value: "Only upon request", label: "Only upon request" },
                                { value: "We do not offer a benefits orientation", label: "We do not offer a benefits orientation" },
                            ],
                        },
                        {
                            id: "r6UB",
                            label: "Who leads the benefits discussions with new hires?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Internal HR/benefits team", label: "Internal HR/benefits team" },
                                { value: "External broker", label: "External broker" },
                                { value: "Insurance carrier representative", label: "Insurance carrier representative" },
                                { value: "Employees review benefits on their own through an online system or platform", label: "Employees review benefits on their own through an online system or platform" },
                                { value: "Not applicable", label: "Not applicable" },
                            ],
                        },
                    ],
                }
            ],
        },
        {
            id: "gPpG-s1-kN6Q",
            name: "Open Enrollment Process",
            sections: [
                {
                    id: "gPpG-s1-kN6Q-s0",
                    title: "Open Enrollment Process",
                    questions: [
                        {
                            id: "2j3P",
                            label: "How long does your Open Enrollment period typically run?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Less than a week", label: "Less than a week" },
                                { value: "1–2 weeks", label: "1–2 weeks" },
                                { value: "3–4 weeks", label: "3–4 weeks" },
                                { value: "Varies by plan year", label: "Varies by plan year" },
                                { value: "Other", label: "Other" },
                            ],
                        },
                        {
                            id: "2ATs",
                            label: "Please specify",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "pr7f",
                            label: "What type of Open Enrollment process do you use?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Passive: Employees are automatically re-enrolled in current plans unless they make changes", label: "Passive: Employees are automatically re-enrolled in current plans unless they make changes" },
                                { value: "Active: Employees must make an election each year to maintain or waive coverage", label: "Active: Employees must make an election each year to maintain or waive coverage" },
                                { value: "Can vary each year", label: "Can vary each year" },
                                { value: "Not sure", label: "Not sure" },
                            ],
                        },
                        {
                            id: "mfsT",
                            label: "Who sets up Open Enrollment in your benefits administration system?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Internal HR/benefits team", label: "Internal HR/benefits team" },
                                { value: "External broker", label: "External broker" },
                                { value: "Insurance carrier", label: "Insurance carrier" },
                                { value: "Benefits technology vendor", label: "Benefits technology vendor" },
                                { value: "Other", label: "Other" },
                            ],
                        },
                        {
                            id: "jgkY",
                            label: "Please specify",
                            type: "text",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "gPpG-s2-6b1N",
            name: "Education & Support",
            sections: [
                {
                    id: "gPpG-s2-6b1N-s0",
                    title: "Education & Support",
                    questions: [
                        {
                            id: "g7ty",
                            label: "What kind of benefits education/support do you provide during Open Enrollment?",
                            type: "checkbox",
                            required: false,
                            options: [
                                { value: "Live virtual sessions", label: "Live virtual sessions" },
                                { value: "In-person sessions", label: "In-person sessions" },
                                { value: "Pre-recorded videos or presentations", label: "Pre-recorded videos or presentations" },
                                { value: "Email guides or FAQ sheets", label: "Email guides or FAQ sheets" },
                                { value: "Other", label: "Other" },
                            ],
                        },
                        {
                            id: "4Nnj",
                            label: "Please specify",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "nVUN",
                            label: "Who leads these employee meetings or communications?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Internal HR/benefits team", label: "Internal HR/benefits team" },
                                { value: "External broker", label: "External broker" },
                                { value: "Insurance carrier", label: "Insurance carrier" },
                                { value: "Not applicable", label: "Not applicable" },
                            ],
                        },
                    ],
                }
            ],
        },
        {
            id: "khFB-s1-9Cu9",
            name: "COBRA / State Continuation",
            sections: [
                {
                    id: "khFB-s1-9Cu9-s0",
                    title: "COBRA / State Continuation",
                    questions: [
                        {
                            id: "uJKk",
                            label: "Who handles COBRA or state continuation administration?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Internal HR/benefits team", label: "Internal HR/benefits team" },
                                { value: "External broker", label: "External broker" },
                                { value: "Payroll vendor", label: "Payroll vendor" },
                                { value: "Integrated with HR/payroll/ben admin system", label: "Integrated with HR/payroll/ben admin system" },
                                { value: "COBRA-specific vendor", label: "COBRA-specific vendor" },
                                { value: "Other", label: "Other" },
                            ],
                        },
                        {
                            id: "59qg",
                            label: "Please specify",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "ocYq",
                            label: "How do you notify COBRA-eligible employees about continuation coverage?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Automatically sent via integrated platform", label: "Automatically sent via integrated platform" },
                                { value: "Sent manually by internal HR", label: "Sent manually by internal HR" },
                                { value: "Sent by broker or COBRA vendor", label: "Sent by broker or COBRA vendor" },
                                { value: "Not sure / No formal process", label: "Not sure / No formal process" },
                            ],
                        },
                    ],
                }
            ],
        },
        {
            id: "khFB-s2-d2Wc",
            name: "Pre-Tax Benefits",
            sections: [
                {
                    id: "khFB-s2-d2Wc-s0",
                    title: "Pre-Tax Benefits",
                    questions: [
                        {
                            id: "i7kn",
                            label: "Which tax-advantaged benefits do you currently offer?",
                            type: "checkbox",
                            required: false,
                            options: [
                                { value: "Health Savings Account (HSA)", label: "Health Savings Account (HSA)" },
                                { value: "Medical FSA", label: "Medical FSA" },
                                { value: "Dependent Care FSA", label: "Dependent Care FSA" },
                                { value: "Limited Purpose FSA", label: "Limited Purpose FSA" },
                                { value: "Health Reimbursement Arrangement (HRA)", label: "Health Reimbursement Arrangement (HRA)" },
                                { value: "Commuter Benefits", label: "Commuter Benefits" },
                                { value: "None", label: "None" },
                            ],
                        },
                        {
                            id: "7FBG",
                            label: "How does the employer contribute to the HSA?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Flat amount", label: "Flat amount" },
                                { value: "Varies by tier (EE, Family)", label: "Varies by tier (EE, Family)" },
                                { value: "Percentage of deductible", label: "Percentage of deductible" },
                                { value: "None", label: "None" },
                                { value: "Other", label: "Other" },
                            ],
                        },
                        {
                            id: "tV7o",
                            label: "Type your question here",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "dCnf",
                            label: "How are HSA contributions administered?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Integrated with HR/payroll/ben admin system", label: "Integrated with HR/payroll/ben admin system" },
                                { value: "Manually entered by internal HR through payroll", label: "Manually entered by internal HR through payroll" },
                                { value: "Direct deposit via HSA provider", label: "Direct deposit via HSA provider" },
                                { value: "Employer sends lump sum to provider", label: "Employer sends lump sum to provider" },
                                { value: "Other", label: "Other" },
                            ],
                        },
                        {
                            id: "apAq",
                            label: "Please specify",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "58p8",
                            label: "How is the HSA contribution funded?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Per paycheck", label: "Per paycheck" },
                                { value: "Monthly", label: "Monthly" },
                                { value: "Quarterly", label: "Quarterly" },
                                { value: "Annual (front-loaded)", label: "Annual (front-loaded)" },
                            ],
                        },
                        {
                            id: "3rkc",
                            label: "How do employees open or access their HSA account?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Employer automatically opens HSA accounts for eligible employees", label: "Employer automatically opens HSA accounts for eligible employees" },
                                { value: "Employees must open their own HSA account with a specified provider", label: "Employees must open their own HSA account with a specified provider" },
                                { value: "Employees can choose their own HSA provider", label: "Employees can choose their own HSA provider" },
                            ],
                        },
                    ],
                }
            ],
        }
    ],
};
