import { FormDataDefinition } from '@/types/form';

/**
 * Medical Coverage Survey Census Sub Form
 * Fillout template ID: 199DTBMrsLus
 * Published URL: https://betafits.fillout.com/t/199DTBMrsLus
 *
 * AUTO-GENERATED by scripts/fetch-fillout-published-structure.ts on 2026-04-17T16:01:36.677Z.
 * Do not edit by hand — regenerate instead so the multi-page wizard layout
 * stays in sync with Fillout.
 */
export const FORM_DATA: FormDataDefinition = {
    id: "199DTBMrsLus",
    title: "Medical Coverage Survey Census Sub Form",
    pages: [
        {
            id: "rzHzRMvaC6",
            name: "Page",
            sections: [
                {
                    id: "rzHzRMvaC6-s0",
                    title: "Page",
                    questions: [
                        {
                            id: "4yptyRTf1voVY7sdFoJxGv",
                            label: "First Name",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "vkabBeFF6JFQzMgZ4GNPVy",
                            label: "Last Name",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "vYP5rMTAgx4DPKvh4NMn9G",
                            label: "Relation",
                            type: "select",
                            required: false,
                        },
                        {
                            id: "qUc44oHzKFJSS5mxgHjNSL",
                            label: "Date of Birth",
                            type: "date",
                            required: false,
                        },
                        {
                            id: "qAuXdq5iYpxy1Bp9jMaDWm",
                            label: "Gender",
                            type: "radio",
                            required: false,
                        },
                    ],
                }
            ],
        }
    ],
};
