import { FormDataDefinition } from '@/types/form';

/**
 * Betafits Quick Start
 * Fillout template ID: eBxXtLZdK4us
 * Published URL: https://betafits.fillout.com/t/eBxXtLZdK4us
 *
 * AUTO-GENERATED by scripts/fetch-fillout-published-structure.ts on 2026-04-17T16:01:44.246Z.
 * Do not edit by hand — regenerate instead so the multi-page wizard layout
 * stays in sync with Fillout.
 */
export const FORM_DATA: FormDataDefinition = {
    id: "eBxXtLZdK4us",
    title: "Betafits Quick Start",
    pages: [
        {
            id: "7EnG",
            name: "cover",
            sections: [
                {
                    id: "7EnG-s0",
                    title: "cover",
                    questions: [
                    ],
                }
            ],
        },
        {
            id: "dYq9h2pVky",
            name: "Company Info",
            sections: [
                {
                    id: "dYq9h2pVky-s0",
                    title: "Company Info",
                    questions: [
                        {
                            id: "khqL",
                            label: "Group Data Record ID",
                            type: "text",
                            required: false,
                        },
                    ],
                },
                {
                    id: "dYq9h2pVky-s2-aXJKfC18T8w5R41HeVzp2K",
                    title: "Contact Information",
                    questions: [
                        {
                            id: "qYvbJrrJqLQjqQnVip6c3N",
                            label: "First Name",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "3khn37NbHQYb7CN6NPgrx2",
                            label: "Last Name",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "2d65uNNeKNqSmZT1k2WVRq",
                            label: "Title",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "jZa7ip7oU533vM2qLWCkZj",
                            label: "Phone",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "ckkAfnKZoQag2Kqf7j71Cq",
                            label: "Email",
                            type: "email",
                            required: false,
                        },
                    ],
                },
                {
                    id: "dYq9h2pVky-s3-2kDxEyF5TGHfny7B5g65BP",
                    title: "Company Information",
                    questions: [
                        {
                            id: "2UCyRd53bWrtdKXAK1XMy6",
                            label: "Company Name",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "ayXo",
                            label: "Address",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "fT94",
                            label: "City",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "hmTa",
                            label: "State / Province",
                            type: "select",
                            required: false,
                        },
                        {
                            id: "wLev",
                            label: "ZIP Code",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "uTuDTocoypgCbQCkcHWUXN",
                            label: "Employer Identification Number (EIN)",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "r1TkXLw3QBZBCkoRHidEPs",
                            label: "Year company founded",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "hf2rRXr8RmGS1o5PFoFJJn",
                            label: "Preferred SIC Code",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "xfBVQncwKZoTzx4FDeHDLR",
                            label: "Preferred NAICS Code",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "jMkzWAv3b9K5VCyGHPsZmw",
                            label: "How many benefit-eligible US employees does the company have?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "onbhhvHYbup9VUBE6eAAaz",
                            label: "Estimated Benefit Eligible EEs",
                            type: "number",
                            required: false,
                        },
                        {
                            id: "87fD37dczxpgzodHMWgvWT",
                            label: "Estimated Medical Enrolled EEs",
                            type: "number",
                            required: false,
                        },
                        {
                            id: "xcqpaj6Sfv98YJFAUiCZ4z",
                            label: "Expected Headcount Growth (next 12 months)",
                            type: "number",
                            required: false,
                        },
                    ],
                },
                {
                    id: "dYq9h2pVky-s4-eC9JEMbFvb7Ke9tpn7C9io",
                    title: "Non-Disclosure Agreement (NDA) (Optional)",
                    questions: [
                        {
                            id: "opsQwCsEVnschNufM581ph",
                            label: "Would you like Betafits to sign an NDA regarding your company and employee information?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "6eWgGjt7iTjtYcnZRfnCjm",
                            label: "What is the full legal name of the company?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "aE23zBVWqLxxKfyZAacKm3",
                            label: "Entity type",
                            type: "select",
                            required: false,
                        },
                        {
                            id: "4eLaFN3YpBRxS1gqEFhqG8",
                            label: "State of formation",
                            type: "select",
                            required: false,
                        },
                        {
                            id: "6jRhRnuZ2kzaWXQEYjccAQ",
                            label: "Will you be the signer for the NDA?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "89C6yaJhUwD2hLhed5Pd9R",
                            label: "NDA Signer's Name",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "52iYqLmZqi87WApC4ZUuM1",
                            label: "NDA Signer's Title",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "uJTQWkaMyr8daPGbwKfGJt",
                            label: "NDA Signer's Email",
                            type: "email",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "rfT8HXL1MM",
            name: "Benefits",
            sections: [
                {
                    id: "rfT8HXL1MM-s1-wk9RQ78TqidD32ZVjNMfdc",
                    title: "Benefits Overview",
                    questions: [
                        {
                            id: "d4wVEowxCpRtdsXr81nFnF",
                            label: "Which of the following benefits do you offer at this time?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "iHxYYn5HYHDvKGH7Ec9Z5L",
                            label: "Renewal month of medical coverage",
                            type: "select",
                            required: false,
                        },
                        {
                            id: "gSmJUwa363oWH5x2Q68ojZ",
                            label: "Desired effective date for quotes (if different than renewal)",
                            type: "select",
                            required: false,
                        },
                        {
                            id: "62Sic2EiCFMVuxwFUM9L1k",
                            label: "How do you currently offer medical benefits?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "7XiD4e9FAysNviYb9ocJQd",
                            label: "What is the medical contribution strategy?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "hRA1LaWSMrrX2irz3r6XXd",
                            label: "Please describe your contribution strategy?",
                            type: "textarea",
                            required: false,
                        },
                        {
                            id: "uaFGXRZwNyovwuXGKsCgDf",
                            label: "Contribution to Employee (% or $)",
                            type: "text",
                            required: false,
                            placeholder: "For Ex. $45, 30%, etc.",
                        },
                        {
                            id: "aJ5QJvpDNyhXNMvoSmVEoT",
                            label: "Contribution to Dependents (% or $)",
                            type: "text",
                            required: false,
                            placeholder: "For Ex. $45, 30%, etc.",
                        },
                        {
                            id: "aByPiuEENQzRDaTFecMkKT",
                            label: "Does the percentage apply only the base plan? Employees pay the full cost to buy up to other plans.",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "b5zjBDR1YeKTq9GaVxQYWv",
                            label: "Do you currently use a PEO?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "mM5ZyS9KeVz83eeqfdHoRn",
                            label: "Which PEO do you use?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "vPgLS18szbAabJNGiwDnev",
                            label: "What PEOs have you evaluated?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "kewbuyogJjkbbQNNXpbtxe",
                            label: "Who is your payroll provider?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "i5Cg",
                            label: "What is your Payroll Frequency?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "eKX8",
                            label: "What is your Benefit Deduction Frequency?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "1DzLVcVYD9X23eBWJguR2p",
                            label: "Do any of the following apply to your company or benefits package?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "iUedSGbFvtuwGorGfJLmoU",
                            label: "Please provide additional details for each selected option",
                            type: "textarea",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "sQDiXRuCd1",
            name: "Upload Documents",
            sections: [
                {
                    id: "sQDiXRuCd1-s1-mkMsfT5LRXqeACHDcniMPM",
                    title: "Document Uploader",
                    questions: [
                        {
                            id: "5gwf",
                            label: "To upload a document, click the + Upload button below.",
                            type: "text",
                            required: false,
                        },
                    ],
                },
                {
                    id: "sQDiXRuCd1-s2-nLC4oJeqtnwxCQhjzb1M5t",
                    title: "Other Instructions",
                    questions: [
                        {
                            id: "8xGZP1oCmeWgPa2GhFquPc",
                            label: "Benefits I.Y.O.W. (In Your Own Words)",
                            type: "file",
                            required: false,
                        },
                        {
                            id: "tP2QxuesGXQswTM8r8LNeV",
                            label: "Is there anything else you would like us to know about your benefits package?",
                            type: "textarea",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "uazR",
            name: "Benefit Preference",
            sections: [
                {
                    id: "uazR-s1-2isr6PqpsxEVXV5yZTVhXC",
                    title: "Benefit Preferences",
                    questions: [
                        {
                            id: "hkZ8KcqU7mWUPnJK3WBybe",
                            label: "In your opinion, what is the ideal number of medical plan options you would like to offer?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "qjLXquRvoppwrWfFrFNEnf",
                            label: "Which of the following plan types do you think you would like to offer?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "h5JdKC6cUHMWkD1NSFtJE4",
                            label: "In choosing a carrier and plans, how important are the following?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "qLpBxT2RxYU81MgD6Qb48P",
                            label: "Which of the following are notable benefits pain points for your company?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "pmcR22jTVUgcBSXBKQGMJq",
                            label: "Which best describes your openness toward employees submitting individual health questionnaires as a part of the quoting process?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "awX85gzf6ywgCQsnu1HAKr",
                            label: "Would you like to gather employee feedback for benchmarking and improving your benefits program?",
                            type: "radio",
                            required: false,
                        },
                    ],
                }
            ],
        }
    ],
};
