import { FormDataDefinition } from '@/types/form';

/**
 * Quick Start (New Benefits) 
 * Template ID: jLwpyNvuB2us
 * URL: https://betafits.fillout.com/t/jLwpyNvuB2us
 *
 * Auto-generated from Fillout form structure.
 * Last updated: 2026-04-17T15:25:29.520Z
 */
export const FORM_DATA: FormDataDefinition = {
    id: "jLwpyNvuB2us",
    title: "Quick Start (New Benefits) ",
    pages: [
        {
            id: "main",
            name: "Quick Start (New Benefits) ",
            sections: [
                {
                    id: "main",
                    title: "Quick Start (New Benefits) ",
                    questions: [
                        {
                            id: "3khn37NbHQYb7CN6NPgrx2",
                            label: "Last Name",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "qYvbJrrJqLQjqQnVip6c3N",
                            label: "First Name",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "2d65uNNeKNqSmZT1k2WVRq",
                            label: "Title",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "jZa7ip7oU533vM2qLWCkZj",
                            label: "Phone",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "ckkAfnKZoQag2Kqf7j71Cq",
                            label: "Email",
                            type: "email",
                            required: false,
                        },
                        {
                            id: "2UCyRd53bWrtdKXAK1XMy6",
                            label: "Company Name",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "jMkzWAv3b9K5VCyGHPsZmw",
                            label: "How many benefit-eligible US Employees does the company have?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "1 - 9", label: "1 - 9" },
                                { value: "10 - 24", label: "10 - 24" },
                                { value: "25 - 49", label: "25 - 49" },
                                { value: "50 - 99", label: "50 - 99" },
                                { value: "100 - 249", label: "100 - 249" },
                                { value: "250 - 499", label: "250 - 499" },
                                { value: "500 - 999", label: "500 - 999" },
                                { value: "1000 - 4999", label: "1000 - 4999" },
                                { value: "5000+", label: "5000+" },
                            ],
                        },
                        {
                            id: "a8LGYWqm6WhmN4ByM9TDHt",
                            label: "What is your company address?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "6eWgGjt7iTjtYcnZRfnCjm",
                            label: "Legal name",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "r5Tp19xjoS2tMUaW63GCJB",
                            label: "State of Formation",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "aE23zBVWqLxxKfyZAacKm3",
                            label: "What is the Entity Type?",
                            type: "select",
                            required: false,
                            options: [
                                { value: "Corporation", label: "Corporation" },
                                { value: "Limited Liability Company (LLC)", label: "Limited Liability Company (LLC)" },
                                { value: "Non-profit Corporation", label: "Non-profit Corporation" },
                                { value: "Public Benefit Corporation (PBC)", label: "Public Benefit Corporation (PBC)" },
                                { value: "Sole Proprietorship", label: "Sole Proprietorship" },
                                { value: "General Partnership (GP)", label: "General Partnership (GP)" },
                                { value: "Limited Partnership (LP)", label: "Limited Partnership (LP)" },
                                { value: "Limited Liability Partnership (LLP)", label: "Limited Liability Partnership (LLP)" },
                                { value: "Limited Liability Limited Partnership (LLLP)", label: "Limited Liability Limited Partnership (LLLP)" },
                                { value: "Professional Corporation (PC)", label: "Professional Corporation (PC)" },
                                { value: "Professional Limited Liability Company (PLLC)", label: "Professional Limited Liability Company (PLLC)" },
                                { value: "Other", label: "Other" },
                                { value: "", label: "" },
                            ],
                        },
                        {
                            id: "iez8bg63WnH294LzHwinHv",
                            label: "What is the Tax Structure?",
                            type: "select",
                            required: false,
                            options: [
                                { value: "C-Corporation", label: "C-Corporation" },
                                { value: "S-Corporation", label: "S-Corporation" },
                                { value: "Partnership", label: "Partnership" },
                                { value: "Individual/Sole Proprietorship", label: "Individual/Sole Proprietorship" },
                                { value: "501(c)(3)", label: "501(c)(3)" },
                                { value: "501(c)(4)", label: "501(c)(4)" },
                                { value: "501(c)(5)", label: "501(c)(5)" },
                                { value: "501(c)(6)", label: "501(c)(6)" },
                            ],
                        },
                        {
                            id: "uTuDTocoypgCbQCkcHWUXN",
                            label: "Employer Identification Number (EIN)",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "hf2rRXr8RmGS1o5PFoFJJn",
                            label: "Preferred SIC Code",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "xfBVQncwKZoTzx4FDeHDLR",
                            label: "Preferred NAICS Code",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "opsQwCsEVnschNufM581ph",
                            label: "Non-Disclosure Agreement (NDA) (Optional)",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Yes", label: "Yes" },
                                { value: "No", label: "No" },
                            ],
                        },
                        {
                            id: "6jRhRnuZ2kzaWXQEYjccAQ",
                            label: "Will you be the signer for the NDA?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Yes", label: "Yes" },
                                { value: "No", label: "No" },
                            ],
                        },
                        {
                            id: "89C6yaJhUwD2hLhed5Pd9R",
                            label: "NDA Signer's Name",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "52iYqLmZqi87WApC4ZUuM1",
                            label: "NDA Signer's Title",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "uJTQWkaMyr8daPGbwKfGJt",
                            label: "NDA Signer's Email",
                            type: "email",
                            required: false,
                        },
                        {
                            id: "kTefLrKMYMqFgSnTi2sruD",
                            label: "Expected Benefit Start Month",
                            type: "select",
                            required: false,
                            options: [
                                { value: "January 1", label: "January 1" },
                                { value: "February 1", label: "February 1" },
                                { value: "March 1", label: "March 1" },
                                { value: "April 1", label: "April 1" },
                                { value: "May 1", label: "May 1" },
                                { value: "June 1", label: "June 1" },
                                { value: "July 1", label: "July 1" },
                                { value: "August 1", label: "August 1" },
                                { value: "September 1", label: "September 1" },
                                { value: "October 1", label: "October 1" },
                                { value: "November 1", label: "November 1" },
                                { value: "December 1", label: "December 1" },
                                { value: "January", label: "January" },
                            ],
                        },
                        {
                            id: "5rTpWrNmhXK7vpf5HrWiTf",
                            label: "Are you currently with a PEO?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Yes", label: "Yes" },
                                { value: "No, we have never considered a PEO", label: "No, we have never considered a PEO" },
                                { value: "No, we have considered but decided against", label: "No, we have considered but decided against" },
                                { value: "Not sure", label: "Not sure" },
                            ],
                        },
                        {
                            id: "vEu5E6WSrh7hr6vNnLtcYc",
                            label: "What PEO are you working with?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Justworks", label: "Justworks" },
                                { value: "ADP TotalSource", label: "ADP TotalSource" },
                                { value: "TriNet", label: "TriNet" },
                                { value: "Insperity", label: "Insperity" },
                                { value: "Sequoia One", label: "Sequoia One" },
                                { value: "Paychex", label: "Paychex" },
                                { value: "Rippling", label: "Rippling" },
                                { value: "PEO Spectrum", label: "PEO Spectrum" },
                            ],
                        },
                        {
                            id: "chZqidnnuADLqDMMhKU6JC",
                            label: "What PEOs have you evaluated?",
                            type: "checkbox",
                            required: false,
                            options: [
                                { value: "Justworks", label: "Justworks" },
                                { value: "ADP TotalSource", label: "ADP TotalSource" },
                                { value: "TriNet", label: "TriNet" },
                                { value: "Insperity", label: "Insperity" },
                                { value: "Sequoia One", label: "Sequoia One" },
                                { value: "Paychex", label: "Paychex" },
                                { value: "Rippling", label: "Rippling" },
                            ],
                        },
                        {
                            id: "odWtJEgDwD2FP72y1hSZAG",
                            label: "Who is your payroll provider?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Rippling", label: "Rippling" },
                                { value: "ADP", label: "ADP" },
                                { value: "Gusto", label: "Gusto" },
                                { value: "Paychex", label: "Paychex" },
                                { value: "Paycor", label: "Paycor" },
                                { value: "Paylocity", label: "Paylocity" },
                                { value: "Form Test", label: "Form Test" },
                            ],
                        },
                        {
                            id: "dyTDunFBzPwYaJ6y1HUNmu",
                            label: "What is your general stance toward employees submitting individual health questionnaires?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "We have done this before and would do it again", label: "We have done this before and would do it again" },
                                { value: "Open to it if it will save us money", label: "Open to it if it will save us money" },
                                { value: "Open to it if it is only for a few employees", label: "Open to it if it is only for a few employees" },
                                { value: "Against it. Too invasive or too much of a hassle.", label: "Against it. Too invasive or too much of a hassle." },
                                { value: "Not Sure", label: "Not Sure" },
                            ],
                        },
                        {
                            id: "jAdrKd4eMWZ2RxiSqKqJK2",
                            label: "In your opinion, what is the ideal number of medical plan options you would like to offer?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "1", label: "1" },
                                { value: "2", label: "2" },
                                { value: "3", label: "3" },
                                { value: "4", label: "4" },
                                { value: "5+", label: "5+" },
                            ],
                        },
                        {
                            id: "6TGDTAjUbJ2pcw6xNBoXWd",
                            label: "Which of the following plan types do you think you would like to offer?",
                            type: "checkbox",
                            required: false,
                            options: [
                                { value: "HDHP with HSA (Bronze)", label: "HDHP with HSA (Bronze)" },
                                { value: "HDHP with HSA (Silver)", label: "HDHP with HSA (Silver)" },
                                { value: " HDHP with HSA (Gold)", label: " HDHP with HSA (Gold)" },
                                { value: "PPO (Bronze)", label: "PPO (Bronze)" },
                                { value: "PPO (Silver)", label: "PPO (Silver)" },
                                { value: "PPO (Gold)", label: "PPO (Gold)" },
                                { value: "HMO", label: "HMO" },
                                { value: "Not Sure", label: "Not Sure" },
                                { value: "wertyui", label: "wertyui" },
                                { value: "fdsa", label: "fdsa" },
                            ],
                        },
                        {
                            id: "7qZbS9oj1TSCcUPCiRbDga",
                            label: "Total Cost (In choosing a carrier and plans, how important are the following?)",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Not Important", label: "Not Important" },
                                { value: "Somewhat Important", label: "Somewhat Important" },
                                { value: "Important", label: "Important" },
                                { value: "Very Important", label: "Very Important" },
                            ],
                        },
                        {
                            id: "1ftkyHoFU66FJYwum7ZHXj",
                            label: "Size of Network (In choosing a carrier and plans, how important are the following?)",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Not Important", label: "Not Important" },
                                { value: "Somewhat Important", label: "Somewhat Important" },
                                { value: "Important", label: "Important" },
                                { value: "Very Important", label: "Very Important" },
                            ],
                        },
                        {
                            id: "ah4qcTmAA8yidznBt5gvha",
                            label: "Telemedicine Access (In choosing a carrier and plans, how important are the following?)",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Not Important", label: "Not Important" },
                                { value: "Somewhat Important", label: "Somewhat Important" },
                                { value: "Important", label: "Important" },
                                { value: "Very Important", label: "Very Important" },
                            ],
                        },
                        {
                            id: "kGQtKVPzWUAszgoSkMsP68",
                            label: "User Experience (In choosing a carrier and plans, how important are the following?)",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Not Important", label: "Not Important" },
                                { value: "Somewhat Important", label: "Somewhat Important" },
                                { value: "Important", label: "Important" },
                                { value: "Very Important", label: "Very Important" },
                            ],
                        },
                        {
                            id: "xcB3nRWdcykviaf5aJnoLN",
                            label: "Value for Money (In choosing a carrier and plans, how important are the following?)",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Not Important", label: "Not Important" },
                                { value: "Somewhat Important", label: "Somewhat Important" },
                                { value: "Important", label: "Important" },
                                { value: "Very Important", label: "Very Important" },
                            ],
                        },
                        {
                            id: "tyNhTBMd1Jw3cUBsyq7Jho",
                            label: "Biggest Name / Market Share (In choosing a carrier and plans, how important are the following?)",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Not Important", label: "Not Important" },
                                { value: "Somewhat Important", label: "Somewhat Important" },
                                { value: "Important", label: "Important" },
                                { value: "Very Important", label: "Very Important" },
                            ],
                        },
                        {
                            id: "1NP2Vxs9EN6WS72ubMa4uD",
                            label: "Mental Health Resources (In choosing a carrier and plans, how important are the following?)",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Not Important", label: "Not Important" },
                                { value: "Somewhat Important", label: "Somewhat Important" },
                                { value: "Important", label: "Important" },
                                { value: "Very Important", label: "Very Important" },
                            ],
                        },
                        {
                            id: "vdhdk1c2U6qRgFMfbEgrbC",
                            label: "Modern Technology (In choosing a carrier and plans, how important are the following?)",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Not Important", label: "Not Important" },
                                { value: "Somewhat Important", label: "Somewhat Important" },
                                { value: "Important", label: "Important" },
                                { value: "Very Important", label: "Very Important" },
                            ],
                        },
                        {
                            id: "oG5d1sEYyqicGUJFT6qvPr",
                            label: "What benefits do you plan to offer at this time?",
                            type: "checkbox",
                            required: false,
                            options: [
                                { value: "Medical", label: "Medical" },
                                { value: "Dental", label: "Dental" },
                                { value: "Vision", label: "Vision" },
                                { value: "401(k)", label: "401(k)" },
                                { value: "Life", label: "Life" },
                                { value: "Disability", label: "Disability" },
                            ],
                        },
                        {
                            id: "6NfiwHmKWDbUkaMzAAJC26",
                            label: "What contribution strategy do you have in mind?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Flat dollar contribution per employee", label: "Flat dollar contribution per employee" },
                                { value: "Flat dollar contribution per employee w/ additional amount for spouses/dependents", label: "Flat dollar contribution per employee w/ additional amount for spouses/dependents" },
                                { value: "Percentage of employee base plan and employee pays the difference for buy-up plan or to add family members", label: "Percentage of employee base plan and employee pays the difference for buy-up plan or to add family members" },
                                { value: "Percentage of all employee plans and a percentage for adding family members", label: "Percentage of all employee plans and a percentage for adding family members" },
                                { value: "Not Sure", label: "Not Sure" },
                            ],
                        },
                        {
                            id: "whhcQxhxkMZRwZJYfVQRRD",
                            label: "Is there anything else you would like us to know about your benefits package?",
                            type: "textarea",
                            required: false,
                        },
                        {
                            id: "p77mtNXwXoYsAT1H1z87iP",
                            label: "Benefits I.Y.O.W. (In Your Own Words)",
                            type: "file",
                            required: false,
                        },
                    ],
                }
            ],
        }
    ],
};
