import { FormDataDefinition } from '@/types/form';

/**
 * Document Upload Sub Form
 * Fillout template ID: aTDkqH7zTmus
 * Published URL: https://betafits.fillout.com/t/aTDkqH7zTmus
 *
 * AUTO-GENERATED by scripts/fetch-fillout-published-structure.ts on 2026-04-17T16:01:43.691Z.
 * Do not edit by hand — regenerate instead so the multi-page wizard layout
 * stays in sync with Fillout.
 */
export const FORM_DATA: FormDataDefinition = {
    id: "aTDkqH7zTmus",
    title: "Document Upload Sub Form",
    pages: [
        {
            id: "ryB2",
            name: "Page",
            sections: [
                {
                    id: "ryB2-s0",
                    title: "Page",
                    questions: [
                        {
                            id: "jFiU",
                            label: "Document Type",
                            type: "select",
                            required: false,
                        },
                        {
                            id: "kZ8Y",
                            label: "To make sure everything is processed correctly, please upload one document at a time. You can submit additional documents right after",
                            type: "file",
                            required: false,
                        },
                        {
                            id: "mG7t",
                            label: "group_id",
                            type: "text",
                            required: false,
                        },
                    ],
                }
            ],
        }
    ],
};
