import { FormDataDefinition } from '@/types/form';

/**
 * Workers Compensation Questionnaire
 * Fillout template ID: tE2Bb3x71Cus
 * Published URL: https://betafits.fillout.com/t/tE2Bb3x71Cus
 *
 * AUTO-GENERATED by scripts/fetch-fillout-published-structure.ts on 2026-04-17T16:01:37.234Z.
 * Do not edit by hand — regenerate instead so the multi-page wizard layout
 * stays in sync with Fillout.
 */
export const FORM_DATA: FormDataDefinition = {
    id: "tE2Bb3x71Cus",
    title: "Workers Compensation Questionnaire",
    pages: [
        {
            id: "u5mn3yiacR",
            name: "Page 2",
            sections: [
                {
                    id: "u5mn3yiacR-s1-7ZKC",
                    title: "Company Information",
                    questions: [
                        {
                            id: "e4WD",
                            label: "Company Name:",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "6YEsahAjzemmBLvBiGPqbQ",
                            label: "Phone:",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "dg99",
                            label: "FEIN:",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "8C36dGtSafJkQFyMdoLotN",
                            label: "DBA:",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "hJ3ns8x5QG2C1kT58SFreu",
                            label: "Email:",
                            type: "email",
                            required: false,
                        },
                        {
                            id: "9rTDWeYHDLuqiEk4XSs6P9",
                            label: "Website:",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "j1eccjcascjGZWLtiE1XdR",
                            label: "Fax:",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "q6xnmgZcKpTjnagzBbzNAb",
                            label: "Physical Address:",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "3LFSMi2bB9nZMSYLLJuDDH",
                            label: "City:",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "8FAo",
                            label: "State",
                            type: "select",
                            required: false,
                        },
                        {
                            id: "igvd3ZJvAhYzQF79Tg2Ubk",
                            label: "Zip:",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "aQ71",
                            label: "Is your mailing address the same as your physical address?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "kRymjtG7VKcDcmK7hmKx2n",
                            label: "Mailing Address:",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "gjZtdpppkNMkaFNykaMRxa",
                            label: "City:",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "n61j",
                            label: "State",
                            type: "select",
                            required: false,
                        },
                        {
                            id: "eeTZrLNZJhsiwfqKSWk8sn",
                            label: "Zip:",
                            type: "text",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "2SEr",
            name: "Operations & Payroll",
            sections: [
                {
                    id: "2SEr-s1-anGB",
                    title: "Operations & Payroll",
                    questions: [
                        {
                            id: "76op",
                            label: "Detailed Description of Operations:",
                            type: "textarea",
                            required: false,
                        },
                        {
                            id: "mzyA",
                            label: "Do your employees handle any type of product, prototypes, machinery, tools, etc?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "vF2Z",
                            label: "What kind of equipment is used?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "8snnXeauHTjC4XhcZwftvY",
                            label: "What state are you incorporated in?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "2p7j",
                            label: "In Business Since (YYYY):",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "cAdG",
                            label: "SIC Code:",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "9xDj",
                            label: "NAICS Code",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "56UB",
                            label: "Do other entities use this FEIN?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "n2QMrYmMsQDrjiihVWDjsr",
                            label: "Additional Company Name",
                            type: "textarea",
                            required: false,
                        },
                        {
                            id: "adA8",
                            label: "Entity Type",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "3QJW",
                            label: "Hours of Operation:",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "gaVf",
                            label: "Pay Frequency:",
                            type: "select",
                            required: false,
                        },
                        {
                            id: "jReW",
                            label: "Current Payroll Provider:",
                            type: "text",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "4WdR",
            name: "Upload Documents",
            sections: [
                {
                    id: "4WdR-s1-fnSJ",
                    title: "Upload Documents",
                    questions: [
                        {
                            id: "usAh",
                            label: "Completed and signed RFP (Request for Proposal).",
                            type: "file",
                            required: false,
                        },
                        {
                            id: "h9bq",
                            label: "Current Payroll Report with deductions and YTD wages.• Report should identify state, workers’ compensation class code, and annual wages",
                            type: "file",
                            required: false,
                        },
                        {
                            id: "jLui",
                            label: "Workers’ Compensation Policy Declaration Page if available.• If currently with a PEO, please provide most recent premium billing statement, or a report detailing payroll by class code and state",
                            type: "file",
                            required: false,
                        },
                        {
                            id: "ryVS",
                            label: "Three to five-year loss runs (valued within last 45-days).• If company has been in business less than three years, or no workers’ compensation experience,• Claims in excess of $25,000, require nature and detail of those claims.",
                            type: "file",
                            required: false,
                        },
                    ],
                }
            ],
        }
    ],
};
