import { FormDataDefinition } from '@/types/form';

/**
 * Betafits Comprehensive Intake Form
 * Fillout template ID: wpjffs7r5pus
 * Published URL: https://betafits.fillout.com/t/wpjffs7r5pus
 *
 * AUTO-GENERATED by scripts/fetch-fillout-published-structure.ts on 2026-04-17T16:01:40.373Z.
 * Do not edit by hand — regenerate instead so the multi-page wizard layout
 * stays in sync with Fillout.
 */
export const FORM_DATA: FormDataDefinition = {
    id: "wpjffs7r5pus",
    title: "Betafits Comprehensive Intake Form",
    pages: [
        {
            id: "nXApCy6nVr",
            name: "Main Page",
            sections: [
                {
                    id: "nXApCy6nVr-s0",
                    title: "Main Page",
                    questions: [
                        {
                            id: "kXUEyWx9AWYbgBQw2Q9sqe",
                            label: "What is your first name?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "jLdKiy15wgdtyZUB4Jc38T",
                            label: "What is your last name?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "8jrHZDeqnveRgrG2xjowcs",
                            label: "What is your title at the company?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "rEWF5qRCMZqWe5vzVx496A",
                            label: "What is your work email?",
                            type: "email",
                            required: false,
                        },
                    ],
                },
                {
                    id: "nXApCy6nVr-s2-qJP6tgDgsnRGjWJSeNjwPS",
                    title: "Company Information",
                    questions: [
                        {
                            id: "sJWdmf7r4raFsLfcpjXiWe",
                            label: "What is the company name?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "rPuGVUBax3DqZvKHqWR4Kj",
                            label: "What is the company address?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "dMx5cR3qTJQLvxaYHvzVFE",
                            label: "Do you have physical locations or active business addresses in any other state(s)?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "b64eD9aKCVwXSnx6yFBN4c",
                            label: "In which other state(s)?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "2XLfhSsc8T8wtvvAxGA8Hd",
                            label: "What year was the company founded?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "ktNAmVGq5jKV6k251MMHhD",
                            label: "Employer Identification Number",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "7t7nvwF28RQd41VAFhaCMt",
                            label: "SIC Code",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "2x1P8FVrLaSZ1h1yzctQvx",
                            label: "NAICS Code",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "u7W18HRWFJJ22qWJYYTuan",
                            label: "What is the company's full legal name?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "j8L1XKc1djZL3i5mE7Bge8",
                            label: "What is the Entity Type?",
                            type: "select",
                            required: false,
                        },
                        {
                            id: "anHLFS6Z1uLM2rMQr4Np5z",
                            label: "What is the Tax Structure?",
                            type: "select",
                            required: false,
                        },
                        {
                            id: "wC3xSLzj1HqzdPm9ZU4Gos",
                            label: "Entity state of formation",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "1XEj9M5RRREzjgNfdP46v8",
                            label: "Is the company a part of any of the following?",
                            type: "checkbox",
                            required: false,
                        },
                    ],
                },
                {
                    id: "nXApCy6nVr-s3-gUm3qWLdsGwvP6rAWrxJNW",
                    title: "Non-Disclosure Agreement (NDA) Optional",
                    questions: [
                        {
                            id: "tc11o2pXix7LFcKCHv73o3",
                            label: "Non-Disclosure Agreement (NDA) (Optional)",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "rJ7KPfPiTjwvpPK9YdWkSo",
                            label: "Will you be the signer for the NDA?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "9agS7ZVuek3K1YhT7f6TyG",
                            label: "NDA Signer's Name",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "kiKmv6AT4S7842grdM5QMf",
                            label: "NDA Signer's Title",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "fwBf6556E6eGzDRKPY14Qt",
                            label: "NDA Signer's Email",
                            type: "email",
                            required: false,
                        },
                    ],
                },
                {
                    id: "nXApCy6nVr-s4-vQ9xsjhJNMcBaEgb6ytd65",
                    title: "Employee Info",
                    questions: [
                        {
                            id: "qMhssvjAnuUkCEnqFUPoTf",
                            label: "How many benefit-eligible US Employees does the company have?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "6418z3aAymx24EFgBfFvRZ",
                            label: "Est. of benefit-eligible EEs",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "oY8abhP2ZU5yLx7XXjek5P",
                            label: "Est. of medical enrolled EEs",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "k42qWo25NC8SQAbqsdXJTw",
                            label: "Expected growth in headcount in next 12 months",
                            type: "text",
                            required: false,
                        },
                    ],
                },
                {
                    id: "nXApCy6nVr-s5-wrrATpYohmoBBMK7tRzEcy",
                    title: "Document Uploader",
                    questions: [
                        {
                            id: "qoamzTPFTTcXEpVPaeWNxp",
                            label: "Upload Plan Summaries and/or Benefits Guide",
                            type: "file",
                            required: false,
                        },
                        {
                            id: "4D4KESQWyCbMd9GMV6vfV4",
                            label: "Upload Invoices",
                            type: "file",
                            required: false,
                        },
                        {
                            id: "jT6qXPuoVu8BJR9jCg3SoM",
                            label: "Upload Employee Census",
                            type: "file",
                            required: false,
                        },
                        {
                            id: "amq634HFjRt7coRWphEtv9",
                            label: "Is there anything else you would like us to know about your benefits package?",
                            type: "textarea",
                            required: false,
                        },
                        {
                            id: "pVCAB4Pq4eUTce8abZG6d1",
                            label: "Benefits I.Y.O.W. (In Your Own Words)",
                            type: "file",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "4NJcphzd8X",
            name: "Submit",
            sections: [
                {
                    id: "4NJcphzd8X-s0",
                    title: "Submit",
                    questions: [
                        {
                            id: "stu29koX23zU7xnNccoBSJ",
                            label: "Is there anything else you would like us to know about your intended benefits package?",
                            type: "textarea",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "6LVYwSsDmi",
            name: "PEO and HR",
            sections: [
                {
                    id: "6LVYwSsDmi-s1-te3KwocirzWndXArhYdhTc",
                    title: "PEO and Payroll",
                    questions: [
                        {
                            id: "4CENC2uJtW1KPRfXGLb2CX",
                            label: "Are you currently with a PEO?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "tvHqVYFNwV9YYfM21MF6cf",
                            label: "Which PEO are you with?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "dYwCF8mZuTXpPvpgC8FskQ",
                            label: "Which PEOs have you evaluated?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "9FS6LprAAfh4wYUunrXgqf",
                            label: "Who is your payroll provider?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "4CbhpKeUCYjrK9kYFYyyjn",
                            label: "Do you use any other HR software separate from your payroll?",
                            type: "checkbox",
                            required: false,
                        },
                    ],
                },
                {
                    id: "6LVYwSsDmi-s2-mQ5DkPeLtkYc4shK8rdMWz",
                    title: "Employer of Record (EOR) Services",
                    questions: [
                        {
                            id: "deTtPbLxBW6YX3F6LcCuMn",
                            label: "Do you use An Employer of Record Service provider?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "2fkt2ZLGA57cYej7JUjZYv",
                            label: "Which EOR provider do you currently use",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "xAZaHWjRm5vWDLjYdLSe1q",
                            label: "In which countries do you currently have multiple EOR employees?",
                            type: "checkbox",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "cDue7NBNVB",
            name: "Benefits Info",
            sections: [
                {
                    id: "cDue7NBNVB-s1-4RitiXWnRcyN2oCXPRsEST",
                    title: "Benefits",
                    questions: [
                        {
                            id: "oCxH5wyvd6VQumDmBYV7B5",
                            label: "Which of these benefits do you currently offer to your employess?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "aMcN4nXFrtgT7bLbu6SbcW",
                            label: "Do you plan to add any of these benefits at this time?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "kbrDFTxExGMQo9D5jKfRjP",
                            label: "What are your major benefit pain points?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "1fwdKjH8VX2LutJbgcN8Fa",
                            label: "Please choose a few ways that would interest you to reinvest potential savings from your benefit costs",
                            type: "checkbox",
                            required: false,
                        },
                    ],
                },
                {
                    id: "cDue7NBNVB-s2-mudiszMGcumgrowBBZCVbA",
                    title: "Medical Plan",
                    questions: [
                        {
                            id: "rnM4BUDwQiBHbzZtyFkC7p",
                            label: "Insurance Renewal of Medical Coverage",
                            type: "select",
                            required: false,
                            placeholder: "Please Select",
                        },
                        {
                            id: "tLV9stuQyKYbS9yWupHWmj",
                            label: "How is your medical plan currently structured?",
                            type: "radio",
                            required: false,
                        },
                    ],
                },
                {
                    id: "cDue7NBNVB-s3-vYUtsaCterWPT32fU2aKgJ",
                    title: "Dental/Vision",
                    questions: [
                        {
                            id: "jjZUuwKnQ1UUbNpdLNXcoG",
                            label: "When was the last time you reviewed rates and carriers for all ancillary lines of coverage?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "dBV1NufgXWbrBn4XWmTWL3",
                            label: "What is your experience with your dental network?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "25gf7WsHx49DjfaHYkWsFG",
                            label: "For a dental policy what sounds more reasonable?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "u55FunQd2AWHpUzRtNAZJF",
                            label: "What are your opinions on covering orthodontics?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "cnx4R9CRhZuavdJNFbqbCK",
                            label: "Experience with vision plan??",
                            type: "radio",
                            required: false,
                        },
                    ],
                },
                {
                    id: "cDue7NBNVB-s4-5VKg6kxaGeYfD4PosF9CR5",
                    title: "Preferences",
                    questions: [
                        {
                            id: "8GxxungxB7Q59ErBFzkutN",
                            label: "What is your general stance toward employees submitting individual health questionnaires to have access to certain health insurance options?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "nZ6QUUNsBUH99q1RVXxW1G",
                            label: "What is your opinion on gathering employee feedback on the benefit package (Pulse survey)",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "5iKwoYUptm69D3khNSJVjZ",
                            label: "In your opinion, what is the ideal number of medical plan options you would like to offer?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "7n2yJ85FSQLa4uUZvrjb1L",
                            label: "Which of the following plan types do you think you would like to offer?",
                            type: "checkbox",
                            required: false,
                        },
                    ],
                },
                {
                    id: "cDue7NBNVB-s5-wrB8u19hm6RQiadkanRHC4",
                    title: "Plan Preferences",
                    questions: [
                        {
                            id: "f5FUrV8B891xHVho9BnxC1",
                            label: "In choosing a carrier and plans, how important are the following?",
                            type: "text",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "rz4ioJY4Ye",
            name: "Eligibility and Contribution",
            sections: [
                {
                    id: "rz4ioJY4Ye-s1-gfLRzyWik1gQtJJP9dVKZW",
                    title: "Eligibility",
                    questions: [
                        {
                            id: "s5xupYk5QpAFYT5SYUvVdX",
                            label: "Which of the following does your workforce include?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "fsW37DZtfebmK1MpwToXaE",
                            label: "How many hours per week are required for benefit eligibility?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "vgkKdxQLTQgaKJeAa27vEh",
                            label: "Are all benefit eligible employees treated the same or do different classes exist?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "tuiVTF5BjuCgC7eHu2mV98",
                            label: "Classes exist for the following?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "492951F98U8RVmo6C9Ni3F",
                            label: "Do you want domestic partners to be eligible for benefits?",
                            type: "radio",
                            required: false,
                        },
                    ],
                },
                {
                    id: "rz4ioJY4Ye-s2-tBA8yhfyEz7eHEtU6j7pSz",
                    title: "Waiting Period",
                    questions: [
                        {
                            id: "caqYeZTuxhXLLPNFt5hA1r",
                            label: "What is your most common benefit waiting period?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "eDKFSsLdbKPueK5JWqJM1A",
                            label: "When do benefits enrollments become effective?",
                            type: "radio",
                            required: false,
                        },
                    ],
                },
                {
                    id: "rz4ioJY4Ye-s3-8FdKEsmM2C8ce7AyJDMgDg",
                    title: "Payroll and Deduction Frequency",
                    questions: [
                        {
                            id: "ek88piYngfK767pv4WsVsS",
                            label: "What is your predominant payroll frequency?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "fH8MJgMUjDNwTZh21NDivU",
                            label: "Do all benefit-eligible employees get paid on the same cycle?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "ue5n2tw2GRAZQuyxpoUkEo",
                            label: "Please select your alternate payroll frequency?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "cw2kfLa8EYSDmxsLRrYNB9",
                            label: "How often are benefit deductions taken?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "cf7aJQQ1ukFDMpPC5N2fV4",
                            label: "What frequency are benefit deductions taken?",
                            type: "radio",
                            required: false,
                        },
                    ],
                },
                {
                    id: "rz4ioJY4Ye-s4-oodFz8WJMuXLe4ikUk8TR2",
                    title: "Medical contribution strategy",
                    questions: [
                        {
                            id: "tmti1tPR2DT58GgdKiHDaV",
                            label: "What is the employer Medical contribution strategy?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "mwBcHregDXxzjBz68X7ZPe",
                            label: "EE only",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "vF2S9jFKtshrNiweU2LNCW",
                            label: "EE + Spouse",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "aD56FMfHDDwjijVy74L8Xt",
                            label: "EE + Child(ren)",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "tXPbNbhz3VmqfobbYu62tS",
                            label: "EE + Family",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "6uoXnPTsrF9N3nWPkg3JUk",
                            label: "EE only",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "gZUrmnXJj6TmD2mwjt13Xi",
                            label: "EE + Spouse",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "2cF7GBiSfoVMERooGzT6XR",
                            label: "EE + Child(ren)",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "xxr5zepMzXs7n8MobfEaR3",
                            label: "EE + Family",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "us9cULgV4mazmYrQjxBSxa",
                            label: "Does this amount apply to a base plan and employees pay the difference to buy up?",
                            type: "radio",
                            required: false,
                        },
                    ],
                },
                {
                    id: "rz4ioJY4Ye-s5-r4sezdwvb3AFCG4DwNbHvL",
                    title: "Dental contribution strategy",
                    questions: [
                        {
                            id: "gko2mwmSTqXMTLr4wthFsu",
                            label: "What is the employer Dental contribution strategy?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "pSxfFndC3VTjLDs6ua7g6U",
                            label: "EE only",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "3NWQM2LsY7b9edSHK5FNpt",
                            label: "EE + Spouse",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "maYDxdNZkJEdELvSnXHCBq",
                            label: "EE + Child(ren)",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "my7T69az2xKgfhjVvvrgfh",
                            label: "EE + Family",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "pXbv181uRG5fETxuxBi5fq",
                            label: "EE only",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "idFMRDFAbVn9aXwKTKY5z1",
                            label: "EE + Spouse",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "t3oMfWGndW3H7XTHaaKtir",
                            label: "EE + Child(ren)",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "ds3kXf8U8NsHFpepQTWTAs",
                            label: "EE + Family",
                            type: "text",
                            required: false,
                        },
                    ],
                },
                {
                    id: "rz4ioJY4Ye-s6-rUiji3GKREkRqnUjcpop5c",
                    title: "Vision contribution strategy",
                    questions: [
                        {
                            id: "9qZFwhmsbhSBoLw4zzdXkT",
                            label: "What is the employer Vision contribution strategy?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "nU67Kb6af3cSqMz88w8bxz",
                            label: "EE only",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "sZ2xzLfhi2npM9oAn2Asev",
                            label: "EE + Spouse",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "hSDhjQrh6MWLmeqtqhTWF9",
                            label: "EE + Child(ren)",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "5kmVLf5WpxgLzAiWP1hjwd",
                            label: "EE + Family",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "1Kegu1vwQjiwfDLugqb4ED",
                            label: "EE only",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "ttvkfcoT5vyyGEWyzXtJNC",
                            label: "EE + Spouse",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "bDktZJUZqYBYAEoj9g9brP",
                            label: "EE + Child(ren)",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "mD3uAHsuUGu2kB2Em4JvBe",
                            label: "EE + Family",
                            type: "text",
                            required: false,
                        },
                    ],
                }
            ],
        }
    ],
};
