import { FormDataDefinition } from '@/types/form';

/**
 * NDA
 * Fillout template ID: 6eUGSndhtYus
 * Published URL: https://betafits.fillout.com/t/6eUGSndhtYus
 *
 * AUTO-GENERATED by scripts/fetch-fillout-published-structure.ts on 2026-04-17T16:17:26.832Z.
 * Do not edit by hand — regenerate instead so the multi-page wizard layout
 * stays in sync with Fillout.
 */
export const FORM_DATA: FormDataDefinition = {
    id: "6eUGSndhtYus",
    title: "NDA",
    pages: [
        {
            id: "sm6SZYJFrc",
            name: "Page",
            sections: [
                {
                    id: "sm6SZYJFrc-s0",
                    title: "Page",
                    questions: [
                        {
                            id: "4a93NzjYMKMaGEo9veT8pV",
                            label: "Non-Disclosure Agreement (NDA) (Optional)",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Yes", label: "Yes" },
                                { value: "No", label: "No" },
                            ],
                        },
                        {
                            id: "akhj",
                            label: "Record ID",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "o19dKvYC9qGMfLEExpoXxf",
                            label: "What is the company's full legal name?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "fmJquAsRkqBxEpnwyZwd4L",
                            label: "What is the entity's state of formation?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "wk639YhY1EEpuZgidtntGq",
                            label: "What is the entity type?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "gAQ1ThdizsjffXvXeL1Yxv",
                            label: "Will you be the signer for the NDA?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Yes", label: "Yes" },
                                { value: "No", label: "No" },
                            ],
                        },
                        {
                            id: "aCC2cW2taXLxHpXPsYYYgm",
                            label: "Name of the NDA Signer",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "teMNcdpmdLWx1psKKqHPV2",
                            label: "Title of the NDA Signer",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "7LD9hA4LaXHZqNYkJ64Gqg",
                            label: "Email of the NDA Signer",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "gQJ57d5ZjWPfej6teQoUuR",
                            label: "What is the Legal Name of the Entity?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "qRv5QPb1PJ2EZ7QYMx5c6A",
                            label: "Entity Type (Corporation, LLC, etc.)",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "4DekuksCczyoSV6gDQ3ATv",
                            label: "What is the Entity State of Formation?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "ccywgV1PQBZqeF8q5VxCkn",
                            label: "Employer Identification Number",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "qXwNuDfp6PMfG1GZfAuTmV",
                            label: "Expected Benefit Start Month or Renewal of Medical Coverage",
                            type: "select",
                            required: false,
                            options: [
                                { value: "January 1", label: "January 1" },
                                { value: "February 1", label: "February 1" },
                                { value: "March 1", label: "March 1" },
                                { value: "April 1", label: "April 1" },
                                { value: "May 1", label: "May 1" },
                                { value: "June 1", label: "June 1" },
                                { value: "July 1", label: "July 1" },
                                { value: "August 1", label: "August 1" },
                                { value: "September 1", label: "September 1" },
                                { value: "October 1", label: "October 1" },
                                { value: "November 1", label: "November 1" },
                                { value: "December 1", label: "December 1" },
                            ],
                        },
                    ],
                }
            ],
        }
    ],
};
