import { FormDataDefinition } from '@/types/form';

/**
 * PEO / EOR Assessment
 * Fillout template ID: cqBbC1vEUcus
 * Published URL: https://betafits.fillout.com/t/cqBbC1vEUcus
 *
 * AUTO-GENERATED by scripts/fetch-fillout-published-structure.ts on 2026-04-17T16:01:39.542Z.
 * Do not edit by hand — regenerate instead so the multi-page wizard layout
 * stays in sync with Fillout.
 */
export const FORM_DATA: FormDataDefinition = {
    id: "cqBbC1vEUcus",
    title: "PEO / EOR Assessment",
    pages: [
        {
            id: "nTAv",
            name: "PEO Info",
            sections: [
                {
                    id: "nTAv-s1-tozw",
                    title: "PEO Information",
                    questions: [
                        {
                            id: "e29p",
                            label: "Do you currently use a PEO?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "tY3h",
                            label: "What were the main reasons you decided not to use a PEO?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "w4Xq",
                            label: "Which PEO do you use?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "pt6E",
                            label: "Would you be open to switching to another PEO or to a payroll-only solution?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "bjGS",
                            label: "Which PEOs have you evaluated?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "bPLT",
                            label: "What are your top considerations when exploring a PEO?",
                            type: "checkbox",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "oFtt",
            name: "EOR Info",
            sections: [
                {
                    id: "oFtt-s1-smvQ",
                    title: "EOR Information",
                    questions: [
                        {
                            id: "okAk",
                            label: "Do you currently use an EOR?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "tyXd",
                            label: "EOR Vendors You’ve Used",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "oswx",
                            label: "Specify other vendor(s)",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "4UzM",
                            label: "EOR Countries & Workforce Details",
                            type: "text",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "soxF",
            name: "Document upload",
            sections: [
                {
                    id: "soxF-s1-h91K",
                    title: "Document Uploads",
                    questions: [
                        {
                            id: "a5L8",
                            label: "Upload current PEO Invoice",
                            type: "file",
                            required: false,
                        },
                        {
                            id: "jZzH",
                            label: "Upload current EOR Invoice",
                            type: "file",
                            required: false,
                        },
                        {
                            id: "84QH",
                            label: "Other details you’d like us to know",
                            type: "textarea",
                            required: false,
                        },
                    ],
                }
            ],
        }
    ],
};
