import { FormDataDefinition } from '@/types/form';

/**
 * Quick Start (New Benefits) 
 * Fillout template ID: jLwpyNvuB2us
 * Published URL: https://betafits.fillout.com/t/jLwpyNvuB2us
 *
 * AUTO-GENERATED by scripts/fetch-fillout-published-structure.ts on 2026-04-17T16:01:42.474Z.
 * Do not edit by hand — regenerate instead so the multi-page wizard layout
 * stays in sync with Fillout.
 */
export const FORM_DATA: FormDataDefinition = {
    id: "jLwpyNvuB2us",
    title: "Quick Start (New Benefits) ",
    pages: [
        {
            id: "dYq9h2pVky",
            name: "Page",
            sections: [
                {
                    id: "dYq9h2pVky-s1-aXJKfC18T8w5R41HeVzp2K",
                    title: "Contact Information",
                    questions: [
                        {
                            id: "qYvbJrrJqLQjqQnVip6c3N",
                            label: "First Name",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "3khn37NbHQYb7CN6NPgrx2",
                            label: "Last Name",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "2d65uNNeKNqSmZT1k2WVRq",
                            label: "Title",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "jZa7ip7oU533vM2qLWCkZj",
                            label: "Phone",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "ckkAfnKZoQag2Kqf7j71Cq",
                            label: "Email",
                            type: "email",
                            required: false,
                        },
                    ],
                },
                {
                    id: "dYq9h2pVky-s2-2kDxEyF5TGHfny7B5g65BP",
                    title: "Company Information",
                    questions: [
                        {
                            id: "2UCyRd53bWrtdKXAK1XMy6",
                            label: "Company Name",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "jMkzWAv3b9K5VCyGHPsZmw",
                            label: "How many benefit-eligible US Employees does the company have?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "a8LGYWqm6WhmN4ByM9TDHt",
                            label: "What is your company address?",
                            type: "text",
                            required: false,
                        },
                    ],
                },
                {
                    id: "dYq9h2pVky-s3-aDkeaanTkqt7LrwoGv4BJC",
                    title: "Entity Information",
                    questions: [
                        {
                            id: "6eWgGjt7iTjtYcnZRfnCjm",
                            label: "Legal name",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "r5Tp19xjoS2tMUaW63GCJB",
                            label: "State of Formation",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "aE23zBVWqLxxKfyZAacKm3",
                            label: "What is the Entity Type?",
                            type: "select",
                            required: false,
                        },
                        {
                            id: "iez8bg63WnH294LzHwinHv",
                            label: "What is the Tax Structure?",
                            type: "select",
                            required: false,
                        },
                        {
                            id: "uTuDTocoypgCbQCkcHWUXN",
                            label: "Employer Identification Number (EIN)",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "hf2rRXr8RmGS1o5PFoFJJn",
                            label: "Preferred SIC Code",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "xfBVQncwKZoTzx4FDeHDLR",
                            label: "Preferred NAICS Code",
                            type: "text",
                            required: false,
                        },
                    ],
                },
                {
                    id: "dYq9h2pVky-s4-eC9JEMbFvb7Ke9tpn7C9io",
                    title: "Non-Disclosure Agreement (NDA)",
                    questions: [
                        {
                            id: "opsQwCsEVnschNufM581ph",
                            label: "Non-Disclosure Agreement (NDA) (Optional)",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "6jRhRnuZ2kzaWXQEYjccAQ",
                            label: "Will you be the signer for the NDA?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "89C6yaJhUwD2hLhed5Pd9R",
                            label: "NDA Signer's Name",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "52iYqLmZqi87WApC4ZUuM1",
                            label: "NDA Signer's Title",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "uJTQWkaMyr8daPGbwKfGJt",
                            label: "NDA Signer's Email",
                            type: "email",
                            required: false,
                        },
                    ],
                },
                {
                    id: "dYq9h2pVky-s5-oWEEBJqfPFsdL1T4ffhr1f",
                    title: "Benefits",
                    questions: [
                        {
                            id: "kTefLrKMYMqFgSnTi2sruD",
                            label: "Expected Benefit Start Month",
                            type: "select",
                            required: false,
                        },
                        {
                            id: "5rTpWrNmhXK7vpf5HrWiTf",
                            label: "Are you currently with a PEO?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "vEu5E6WSrh7hr6vNnLtcYc",
                            label: "What PEO are you working with?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "chZqidnnuADLqDMMhKU6JC",
                            label: "What PEOs have you evaluated?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "odWtJEgDwD2FP72y1hSZAG",
                            label: "Who is your payroll provider?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "dyTDunFBzPwYaJ6y1HUNmu",
                            label: "What is your general stance toward employees submitting individual health questionnaires?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "jAdrKd4eMWZ2RxiSqKqJK2",
                            label: "In your opinion, what is the ideal number of medical plan options you would like to offer?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "6TGDTAjUbJ2pcw6xNBoXWd",
                            label: "Which of the following plan types do you think you would like to offer?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "nBTRLqNSxYhXDggoR7CXAK",
                            label: "In choosing a carrier and plans, how important are the following?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "oG5d1sEYyqicGUJFT6qvPr",
                            label: "What benefits do you plan to offer at this time?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "6NfiwHmKWDbUkaMzAAJC26",
                            label: "What contribution strategy do you have in mind?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "whhcQxhxkMZRwZJYfVQRRD",
                            label: "Is there anything else you would like us to know about your benefits package?",
                            type: "textarea",
                            required: false,
                        },
                        {
                            id: "p77mtNXwXoYsAT1H1z87iP",
                            label: "Benefits I.Y.O.W. (In Your Own Words)",
                            type: "file",
                            required: false,
                        },
                    ],
                }
            ],
        }
    ],
};
