import { FormDataDefinition } from '@/types/form';

/**
 * Benefits Administration
 * Fillout template ID: fYJ3MNj7VQus
 * Published URL: https://betafits.fillout.com/t/fYJ3MNj7VQus
 *
 * AUTO-GENERATED by scripts/fetch-fillout-published-structure.ts on 2026-04-17T16:01:38.313Z.
 * Do not edit by hand — regenerate instead so the multi-page wizard layout
 * stays in sync with Fillout.
 */
export const FORM_DATA: FormDataDefinition = {
    id: "fYJ3MNj7VQus",
    title: "Benefits Administration",
    pages: [
        {
            id: "4pSAP3RVqR",
            name: "Page 1",
            sections: [
                {
                    id: "4pSAP3RVqR-s1-eepx",
                    title: "Carrier & Payroll Processes",
                    questions: [
                        {
                            id: "pmLe",
                            label: "How are benefit carrier updates managed and who is responsible for submitting them?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "gT66",
                            label: "Please specify",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "sYyR",
                            label: "How are payroll deduction changes managed and who is responsible for completing them?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "313V",
                            label: "Please specify",
                            type: "text",
                            required: false,
                        },
                    ],
                },
                {
                    id: "4pSAP3RVqR-s2-uKk2",
                    title: "Enrollment & Deduction Audits",
                    questions: [
                        {
                            id: "4vFw",
                            label: "How do you perform enrollment and deduction audits (e.g., confirming employees are properly enrolled and deductions are accurate)?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "iPzP",
                            label: "Please specify",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "s5oB",
                            label: "How frequently do you audit enrollments?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "nSQt",
                            label: "How frequently do you audit payroll deductions?",
                            type: "radio",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "bhvo",
            name: "Page 2",
            sections: [
                {
                    id: "bhvo-s1-pWVs",
                    title: "New Hire Benefits Communication",
                    questions: [
                        {
                            id: "qMuK",
                            label: "How is your benefits guide shared with employees?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "46Ef",
                            label: "Who creates or updates your benefit guide?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "bgfx",
                            label: "Please specify",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "fNU6",
                            label: "What type of email communication is sent to new hires about their benefits?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "5BXX",
                            label: "When are benefits instructions typically sent to new hires?",
                            type: "radio",
                            required: false,
                        },
                    ],
                },
                {
                    id: "bhvo-s2-iEt4",
                    title: "Orientation & Support",
                    questions: [
                        {
                            id: "pdzn",
                            label: "How do you deliver benefits orientation to new hires?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "r6UB",
                            label: "Who leads the benefits discussions with new hires?",
                            type: "radio",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "gPpG",
            name: "Page 3",
            sections: [
                {
                    id: "gPpG-s1-kN6Q",
                    title: "Open Enrollment Process",
                    questions: [
                        {
                            id: "2j3P",
                            label: "How long does your Open Enrollment period typically run?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "2ATs",
                            label: "Please specify",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "pr7f",
                            label: "What type of Open Enrollment process do you use?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "mfsT",
                            label: "Who sets up Open Enrollment in your benefits administration system?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "jgkY",
                            label: "Please specify",
                            type: "text",
                            required: false,
                        },
                    ],
                },
                {
                    id: "gPpG-s2-6b1N",
                    title: "Education & Support",
                    questions: [
                        {
                            id: "g7ty",
                            label: "What kind of benefits education/support do you provide during Open Enrollment?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "4Nnj",
                            label: "Please specify",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "nVUN",
                            label: "Who leads these employee meetings or communications?",
                            type: "radio",
                            required: false,
                        },
                    ],
                }
            ],
        },
        {
            id: "khFB",
            name: "Page 4",
            sections: [
                {
                    id: "khFB-s1-9Cu9",
                    title: "COBRA / State Continuation",
                    questions: [
                        {
                            id: "uJKk",
                            label: "Who handles COBRA or state continuation administration?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "59qg",
                            label: "Please specify",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "ocYq",
                            label: "How do you notify COBRA-eligible employees about continuation coverage?",
                            type: "radio",
                            required: false,
                        },
                    ],
                },
                {
                    id: "khFB-s2-d2Wc",
                    title: "Pre-Tax Benefits",
                    questions: [
                        {
                            id: "i7kn",
                            label: "Which tax-advantaged benefits do you currently offer?",
                            type: "checkbox",
                            required: false,
                        },
                        {
                            id: "7FBG",
                            label: "How does the employer contribute to the HSA?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "tV7o",
                            label: "Type your question here",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "dCnf",
                            label: "How are HSA contributions administered?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "apAq",
                            label: "Please specify",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "58p8",
                            label: "How is the HSA contribution funded?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "3rkc",
                            label: "How do employees open or access their HSA account?",
                            type: "radio",
                            required: false,
                        },
                    ],
                }
            ],
        }
    ],
};
