import { FormDataDefinition } from '@/types/form';

/**
 * Medical Coverage Survey Census Sub Form
 * Fillout template ID: 199DTBMrsLus
 * Published URL: https://betafits.fillout.com/t/199DTBMrsLus
 *
 * AUTO-GENERATED by scripts/fetch-fillout-published-structure.ts on 2026-04-17T20:57:10.256Z.
 * Do not edit by hand — regenerate instead so the multi-page wizard layout
 * stays in sync with Fillout.
 */
export const FORM_DATA: FormDataDefinition = {
    id: "199DTBMrsLus",
    title: "Medical Coverage Survey Census Sub Form",
    pages: [
        {
            id: "rzHzRMvaC6",
            name: "Page",
            sections: [
                {
                    id: "rzHzRMvaC6-s0",
                    title: "Page",
                    questions: [
                        {
                            id: "4yptyRTf1voVY7sdFoJxGv",
                            label: "First Name",
                            type: "text",
                            required: true,
                            validation: [{ type: 'required', message: "First Name is required" }],
                        },
                        {
                            id: "vkabBeFF6JFQzMgZ4GNPVy",
                            label: "Last Name",
                            type: "text",
                            required: true,
                            validation: [{ type: 'required', message: "Last Name is required" }],
                        },
                        {
                            id: "vYP5rMTAgx4DPKvh4NMn9G",
                            label: "Relation",
                            type: "select",
                            required: true,
                            options: [
                                { value: "Employee", label: "Employee" },
                                { value: "Spouse", label: "Spouse" },
                                { value: "Dependent", label: "Dependent" },
                            ],
                            validation: [{ type: 'required', message: "Relation is required" }],
                        },
                        {
                            id: "qUc44oHzKFJSS5mxgHjNSL",
                            label: "Date of Birth",
                            type: "date",
                            required: true,
                            validation: [{ type: 'required', message: "Date of Birth is required" }],
                        },
                        {
                            id: "qAuXdq5iYpxy1Bp9jMaDWm",
                            label: "Gender",
                            type: "radio",
                            required: true,
                            options: [
                                { value: "Male", label: "Male" },
                                { value: "Female", label: "Female" },
                                { value: "Prefer not to answer", label: "Prefer not to answer" },
                            ],
                            validation: [{ type: 'required', message: "Gender is required" }],
                        },
                    ],
                }
            ],
        }
    ],
};
