import { FormDataDefinition } from '@/types/form';

/**
 * NDA
 * Fillout template ID: 6eUGSndhtYus
 * Published URL: https://betafits.fillout.com/t/6eUGSndhtYus
 *
 * AUTO-GENERATED by scripts/fetch-fillout-published-structure.ts on 2026-04-17T16:01:45.222Z.
 * Do not edit by hand — regenerate instead so the multi-page wizard layout
 * stays in sync with Fillout.
 */
export const FORM_DATA: FormDataDefinition = {
    id: "6eUGSndhtYus",
    title: "NDA",
    pages: [
        {
            id: "sm6SZYJFrc",
            name: "Page",
            sections: [
                {
                    id: "sm6SZYJFrc-s0",
                    title: "Page",
                    questions: [
                        {
                            id: "4a93NzjYMKMaGEo9veT8pV",
                            label: "Non-Disclosure Agreement (NDA) (Optional)",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "akhj",
                            label: "Record ID",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "o19dKvYC9qGMfLEExpoXxf",
                            label: "What is the company's full legal name?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "fmJquAsRkqBxEpnwyZwd4L",
                            label: "What is the entity's state of formation?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "wk639YhY1EEpuZgidtntGq",
                            label: "What is the entity type?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "gAQ1ThdizsjffXvXeL1Yxv",
                            label: "Will you be the signer for the NDA?",
                            type: "radio",
                            required: false,
                        },
                        {
                            id: "aCC2cW2taXLxHpXPsYYYgm",
                            label: "Name of the NDA Signer",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "teMNcdpmdLWx1psKKqHPV2",
                            label: "Title of the NDA Signer",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "7LD9hA4LaXHZqNYkJ64Gqg",
                            label: "Email of the NDA Signer",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "gQJ57d5ZjWPfej6teQoUuR",
                            label: "What is the Legal Name of the Entity?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "qRv5QPb1PJ2EZ7QYMx5c6A",
                            label: "Entity Type (Corporation, LLC, etc.)",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "4DekuksCczyoSV6gDQ3ATv",
                            label: "What is the Entity State of Formation?",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "ccywgV1PQBZqeF8q5VxCkn",
                            label: "Employer Identification Number",
                            type: "text",
                            required: false,
                        },
                        {
                            id: "qXwNuDfp6PMfG1GZfAuTmV",
                            label: "Expected Benefit Start Month or Renewal of Medical Coverage",
                            type: "select",
                            required: false,
                        },
                    ],
                }
            ],
        }
    ],
};
