import { FormDataDefinition } from '@/types/form';

/**
 * Broker Role 
 * Fillout template ID: urHF8xDu7eus
 * Published URL: https://betafits.fillout.com/t/urHF8xDu7eus
 *
 * AUTO-GENERATED by scripts/fetch-fillout-published-structure.ts on 2026-04-17T20:57:16.651Z.
 * Do not edit by hand — regenerate instead so the multi-page wizard layout
 * stays in sync with Fillout.
 */
export const FORM_DATA: FormDataDefinition = {
    id: "urHF8xDu7eus",
    title: "Broker Role ",
    pages: [
        {
            id: "nZ7dDkXjzR-s1-vdyg",
            name: "General Broker Info",
            sections: [
                {
                    id: "nZ7dDkXjzR-s1-vdyg-s0",
                    title: "General Broker Info",
                    questions: [
                        {
                            id: "iuLc",
                            label: "What type of broker, platform, or consultant supports your employee benefits?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Small Firm", label: "Small Firm" },
                                { value: "City or Regional Brokerage", label: "City or Regional Brokerage" },
                                { value: "National Brokerage", label: "National Brokerage" },
                                { value: "Payroll Provider", label: "Payroll Provider" },
                            ],
                        },
                    ],
                }
            ],
        },
        {
            id: "nZ7dDkXjzR-s2-ehMu",
            name: "Agreements and Compensation",
            sections: [
                {
                    id: "nZ7dDkXjzR-s2-ehMu-s0",
                    title: "Agreements and Compensation",
                    questions: [
                        {
                            id: "q7SL",
                            label: "Do you have a signed service agreement or only a Broker of Record (BOR) letter?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Yes", label: "Yes" },
                                { value: "No", label: "No" },
                            ],
                        },
                        {
                            id: "1BQA",
                            label: "Do you pay your broker any fees beyond commissions or standard premiums?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Yes", label: "Yes" },
                                { value: "No", label: "No" },
                            ],
                        },
                        {
                            id: "kFtK",
                            label: "Does your broker currently pay for or subsidize any of the following services?",
                            type: "checkbox",
                            required: false,
                            options: [
                                { value: "HR Support Line", label: "HR Support Line" },
                                { value: "Benefits App", label: "Benefits App" },
                                { value: "COBRA Administration", label: "COBRA Administration" },
                                { value: "HRA Administration", label: "HRA Administration" },
                                { value: "Benefits Administration Platform", label: "Benefits Administration Platform" },
                            ],
                        },
                    ],
                }
            ],
        },
        {
            id: "wF1g-s1-azu1",
            name: "Communication & Admin Support",
            sections: [
                {
                    id: "wF1g-s1-azu1-s0",
                    title: "Communication & Admin Support",
                    questions: [
                        {
                            id: "ucXn",
                            label: "How often do you contact your broker for support?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Weekly or more", label: "Weekly or more" },
                                { value: "Monthly", label: "Monthly" },
                                { value: "Quarterly", label: "Quarterly" },
                                { value: "As needed", label: "As needed" },
                                { value: "Not sure", label: "Not sure" },
                            ],
                        },
                        {
                            id: "oXHq",
                            label: "How often do you have strategic or renewal meetings with your broker?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "Weekly or more", label: "Weekly or more" },
                                { value: "Monthly", label: "Monthly" },
                                { value: "Quarterly", label: "Quarterly" },
                                { value: "As needed", label: "As needed" },
                                { value: "Not sure", label: "Not sure" },
                            ],
                        },
                        {
                            id: "17Hj",
                            label: "Which of the following services does your broker currently provide?",
                            type: "checkbox",
                            required: false,
                            options: [
                                { value: "Renewal negotiations", label: "Renewal negotiations" },
                                { value: "Plan design strategy", label: "Plan design strategy" },
                                { value: "Employee education & communication", label: "Employee education & communication" },
                                { value: "Carrier escalations", label: "Carrier escalations" },
                                { value: "Compliance support (ACA, Section 125, etc.)", label: "Compliance support (ACA, Section 125, etc.)" },
                                { value: "Technology integrations", label: "Technology integrations" },
                                { value: "None of the above", label: "None of the above" },
                            ],
                        },
                    ],
                }
            ],
        },
        {
            id: "siK1-s1-shWv",
            name: "Broker Evaluation & Satisfaction",
            sections: [
                {
                    id: "siK1-s1-shWv-s0",
                    title: "Broker Evaluation & Satisfaction",
                    questions: [
                        {
                            id: "4vRz",
                            label: "How would you rate your broker’s responsiveness and communication?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "1", label: "1" },
                                { value: "2", label: "2" },
                                { value: "3", label: "3" },
                                { value: "4", label: "4" },
                                { value: "5", label: "5" },
                                { value: "6", label: "6" },
                                { value: "7", label: "7" },
                                { value: "8", label: "8" },
                                { value: "9", label: "9" },
                                { value: "10", label: "10" },
                            ],
                        },
                        {
                            id: "9Xgb",
                            label: "How would you rate your broker’s renewal strategy and plan benchmarking?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "1", label: "1" },
                                { value: "2", label: "2" },
                                { value: "3", label: "3" },
                                { value: "4", label: "4" },
                                { value: "5", label: "5" },
                                { value: "6", label: "6" },
                                { value: "7", label: "7" },
                                { value: "8", label: "8" },
                                { value: "9", label: "9" },
                                { value: "10", label: "10" },
                            ],
                        },
                        {
                            id: "mDVP",
                            label: "How would you rate your broker’s compliance and documentation support?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "1", label: "1" },
                                { value: "2", label: "2" },
                                { value: "3", label: "3" },
                                { value: "4", label: "4" },
                                { value: "5", label: "5" },
                                { value: "6", label: "6" },
                                { value: "7", label: "7" },
                                { value: "8", label: "8" },
                                { value: "9", label: "9" },
                                { value: "10", label: "10" },
                            ],
                        },
                        {
                            id: "6aHN",
                            label: "How would you rate your broker’s admin coordination and day-to-day support?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "1", label: "1" },
                                { value: "2", label: "2" },
                                { value: "3", label: "3" },
                                { value: "4", label: "4" },
                                { value: "5", label: "5" },
                                { value: "6", label: "6" },
                                { value: "7", label: "7" },
                                { value: "8", label: "8" },
                                { value: "9", label: "9" },
                                { value: "10", label: "10" },
                            ],
                        },
                        {
                            id: "1YiE",
                            label: "How would you rate your broker’s value as a strategic partner?",
                            type: "radio",
                            required: false,
                            options: [
                                { value: "1", label: "1" },
                                { value: "2", label: "2" },
                                { value: "3", label: "3" },
                                { value: "4", label: "4" },
                                { value: "5", label: "5" },
                                { value: "6", label: "6" },
                                { value: "7", label: "7" },
                                { value: "8", label: "8" },
                                { value: "9", label: "9" },
                                { value: "10", label: "10" },
                            ],
                        },
                        {
                            id: "aJXW",
                            label: "Please upload any broker documentation you have (e.g., signed service agreement or CAA compensation disclosure).",
                            type: "file",
                            required: false,
                        },
                    ],
                }
            ],
        }
    ],
};
