/**
 * AUTO-GENERATED by scripts/build-fillout-airtable-mapping.ts on 2026-04-17T16:17:46.466Z.
 * Per-form mapping of Fillout question IDs -> Airtable field names.
 *
 * Regenerate:
 *   npx tsx scripts/fetch-fillout-form-structure.ts --from-airtable
 *   npx tsx scripts/build-fillout-airtable-mapping.ts
 */

export const FILLOUT_QUESTION_ID_TO_AIRTABLE_FIELD: Record<string, Record<string, string>> = {
    "199DTBMrsLus": {
        "4yptyRTf1voVY7sdFoJxGv": "First Name", // First Name
        "vkabBeFF6JFQzMgZ4GNPVy": "Last Name", // Last Name
        "qUc44oHzKFJSS5mxgHjNSL": "Additional Notes (Optional)", // Date of Birth
        "vYP5rMTAgx4DPKvh4NMn9G": "Additional Notes (Optional)", // Relation
        "qAuXdq5iYpxy1Bp9jMaDWm": "Additional Notes (Optional)", // Gender
    },
    "tE2Bb3x71Cus": {
        "e4WD": "Company Name", // Company Name:
        "dg99": "EIN", // FEIN:
        "6YEsahAjzemmBLvBiGPqbQ": "Phone Number", // Phone:
        "8C36dGtSafJkQFyMdoLotN": "Doing Business As (DBA)", // DBA:
        "9rTDWeYHDLuqiEk4XSs6P9": "Website", // Website:
        "hJ3ns8x5QG2C1kT58SFreu": "Email", // Email:
        "j1eccjcascjGZWLtiE1XdR": "Fax", // Fax:
        "q6xnmgZcKpTjnagzBbzNAb": "Street Address", // Physical Address:
        "8FAo": "State / Province", // State
        "3LFSMi2bB9nZMSYLLJuDDH": "City", // City:
        "igvd3ZJvAhYzQF79Tg2Ubk": "ZIP Code", // Zip: (1)
        "aQ71": "Is Benefit Deduction Frequency the Same as Payroll Frequency?", // Is your mailing address the same as your physical address?
        "kRymjtG7VKcDcmK7hmKx2n": "Mailing Address", // Mailing Address:
        "n61j": "State (Mail Address)", // State (1)
        "gjZtdpppkNMkaFNykaMRxa": "City", // City: (1)
        "eeTZrLNZJhsiwfqKSWk8sn": "ZIP Code", // Zip:
        "76op": "Business Operations Description", // Detailed Description of Operations:
        "mzyA": "Do Your Employees Handle Any Type of Product, Prototypes, Machinery, Tools, Etc.?", // Do your employees handle any type of product, prototypes, machinery, tools, etc?
        "vF2Z": "What Kind of Equipment is Used?", // What kind of equipment is used?
        "8snnXeauHTjC4XhcZwftvY": "What State Are You Incorporated In?", // What state are you incorporated in?
        "2p7j": "In Business Since (YYYY)", // In Business Since (YYYY):
        "9xDj": "NAICS Code", // NAICS Code
        "cAdG": "SIC Code", // SIC Code:
        "56UB": "Do Other Entities Use This FEIN?", // Do other entities use this FEIN?
        "n2QMrYmMsQDrjiihVWDjsr": "Additional Company Name", // Additional Company Name
        "adA8": "Entity Type", // Entity Type
        "3QJW": "Hours of Operation", // Hours of Operation:
        "gaVf": "Payroll Frequency", // Pay Frequency:
        "jReW": "Current Payroll Provider", // Current Payroll Provider:
        "usAh": "Completed and Signed RFP (Request for Proposal)", // Completed and signed RFP (Request for Proposal).
        "h9bq": "Additional Notes (Optional)", // Current Payroll Report with deductions and YTD wages.• Report should identify st
        "jLui": "Additional Notes (Optional)", // Workers’ Compensation Policy Declaration Page if available.• If currently with a
        "ryVS": "Additional Notes (Optional)", // Three to five-year loss runs (valued within last 45-days).• If company has been 
    },
    "xn4WCJ9D8pus": {
        "vATB": "Company Name", // Company Name
        "2uHd": "Link to Users", // Link to Users
        "jf4z": "Link to Assigned Forms", // Link to Assigned Forms
        "rT74": "Document type test", // Document Type
        "vr6K": "Upload New Group Document", // Upload New Group Document
        "ewYV": "Upload New Group Document", // Upload Group's Document
    },
    "fYJ3MNj7VQus": {
        "pmLe": "Additional Notes (Optional)", // How are benefit carrier updates managed and who is responsible for submitting th
        "gT66": "Additional Notes (Optional)", // Please specify (7)
        "sYyR": "Additional Notes (Optional)", // How are payroll deduction changes managed and who is responsible for completing 
        "313V": "Additional Notes (Optional)", // Please specify (6)
        "4vFw": "Additional Notes (Optional)", // How do you perform enrollment and deduction audits (e.g., confirming employees a
        "iPzP": "Additional Notes (Optional)", // Please specify (8)
        "s5oB": "Additional Notes (Optional)", // How frequently do you audit enrollments?
        "nSQt": "Additional Notes (Optional)", // How frequently do you audit payroll deductions?
        "qMuK": "Additional Notes (Optional)", // How is your benefits guide shared with employees?
        "46Ef": "Additional Notes (Optional)", // Who creates or updates your benefit guide?
        "bgfx": "Additional Notes (Optional)", // Please specify
        "fNU6": "Additional Notes (Optional)", // What type of email communication is sent to new hires about their benefits?
        "5BXX": "Additional Notes (Optional)", // When are benefits instructions typically sent to new hires?
        "pdzn": "Additional Notes (Optional)", // How do you deliver benefits orientation to new hires?
        "r6UB": "Additional Notes (Optional)", // Who leads the benefits discussions with new hires?
        "2j3P": "Additional Notes (Optional)", // How long does your Open Enrollment period typically run?
        "2ATs": "Additional Notes (Optional)", // Please specify (1)
        "pr7f": "Additional Notes (Optional)", // What type of Open Enrollment process do you use?
        "mfsT": "Additional Notes (Optional)", // Who sets up Open Enrollment in your benefits administration system?
        "jgkY": "Additional Notes (Optional)", // Please specify (3)
        "g7ty": "Additional Notes (Optional)", // What kind of benefits education/support do you provide during Open Enrollment?
        "4Nnj": "Additional Notes (Optional)", // Please specify (2)
        "nVUN": "Additional Notes (Optional)", // Who leads these employee meetings or communications?
        "uJKk": "Additional Notes (Optional)", // Who handles COBRA or state continuation administration?
        "59qg": "Additional Notes (Optional)", // Please specify (4)
        "ocYq": "Additional Notes (Optional)", // How do you notify COBRA-eligible employees about continuation coverage?
        "i7kn": "How Do You Currently Offer Medical Benefits?", // Which tax-advantaged benefits do you currently offer?
        "7FBG": "Additional Notes (Optional)", // How does the employer contribute to the HSA?
        "tV7o": "Additional Notes (Optional)", // Type your question here
        "dCnf": "Additional Notes (Optional)", // How are HSA contributions administered?
        "apAq": "Additional Notes (Optional)", // Please specify (5)
        "58p8": "Additional Notes (Optional)", // How is the HSA contribution funded?
        "3rkc": "Additional Notes (Optional)", // How do employees open or access their HSA account?
    },
    "ujTSx72pr5us": {
        "fpKM": "Additional Notes (Optional)", // How would you describe the level of compliance support you currently receive fro
        "svnT": "Additional Notes (Optional)", // What systems or methods are used to track your compliance-related tasks througho
        "wVUD": "Additional Notes (Optional)", // What are your primary sources for staying informed about benefits compliance req
        "dc3Q": "Additional Notes (Optional)", // Who manages your ERISA Wrap Document and ensures it is updated?
        "1nxi": "Additional Notes (Optional)", // How is your Section 125 (Premium Only Plan) Document prepared and kept current?
        "9MSF": "Additional Notes (Optional)", // How is your Health & Welfare Form 5500 prepared and filed?
        "vHX9": "Additional Notes (Optional)", // Who prepares and files your ACA Forms 1094/1095?
        "1J9u": "Additional Notes (Optional)", // Is the cost of employer-sponsored healthcare coverage reported on employees W-2s
        "4K16": "Additional Notes (Optional)", // How are required annual notices delivered to employees?
        "6vNE": "Additional Notes (Optional)", // Do you conduct annual non-discrimination testing for your Health & Welfare plans
        "fMAe": "Additional Notes (Optional)", // How is annual non-discrimination testing for your Health & Welfare plans handled
        "mbNe": "Additional Notes (Optional)", // 1095-B Reporting (How are the following compliance requirements currently handle
        "hTTa": "Additional Notes (Optional)", // PCORI Filing (How are the following compliance requirements currently handled?)
        "tcDK": "Additional Notes (Optional)", // RxDC Reporting (How are the following compliance requirements currently handled?
        "uVBo": "Additional Notes (Optional)", // State-Mandated Benefits Reporting (How are the following compliance requirements
        "vZ8p": "Additional Notes (Optional)", // How do you manage compliance with Paid Leave and other employment-related laws a
        "nbY1": "Additional Notes (Optional)", // What systems or partners help you track and administer leave laws?
    },
    "cqBbC1vEUcus": {
        "e29p": "Do You Currently Use An EOR?", // Do you currently use a PEO?
        "tY3h": "Additional Notes (Optional)", // What were the main reasons you decided not to use a PEO?
        "w4Xq": "Which EOR Do You Use?", // Which PEO do you use?
        "pt6E": "Would You Be Open to Switching to Another PEO or to a Payroll-Only Solution?", // Would you be open to switching to another PEO or to a payroll-only solution?
        "bjGS": "Additional Notes (Optional)", // Which PEOs have you evaluated?
        "bPLT": "Additional Notes (Optional)", // What are your top considerations when exploring a PEO?
        "okAk": "Do You Currently Use An EOR?", // Do you currently use an EOR?
        "tyXd": "EOR Vendors You’ve Used", // EOR Vendors You’ve Used
        "oswx": "Specify Other Vendor(s)", // Specify other vendor(s)
        "4UzM": "Additional Notes (Optional)", // EOR Countries & Workforce Details
        "a5L8": "Upload PEO Invoice", // Upload current PEO Invoice
        "jZzH": "Upload EOR Invoice", // Upload current EOR Invoice
        "84QH": "Additional Notes (Optional)", // Other details you’d like us to know
    },
    "wpjffs7r5pus": {
        "jLdKiy15wgdtyZUB4Jc38T": "Additional Notes (Optional)", // What is your last name?
        "kXUEyWx9AWYbgBQw2Q9sqe": "Additional Notes (Optional)", // What is your first name?
        "8jrHZDeqnveRgrG2xjowcs": "Additional Notes (Optional)", // What is your title at the company?
        "rEWF5qRCMZqWe5vzVx496A": "Additional Notes (Optional)", // What is your work email?
        "sJWdmf7r4raFsLfcpjXiWe": "Additional Notes (Optional)", // What is the company name?
        "rPuGVUBax3DqZvKHqWR4Kj": "Additional Notes (Optional)", // What is the company address?
        "dMx5cR3qTJQLvxaYHvzVFE": "Additional Notes (Optional)", // Do you have physical locations or active business addresses in any other state(s
        "b64eD9aKCVwXSnx6yFBN4c": "Additional Notes (Optional)", // In which other state(s)?
        "2XLfhSsc8T8wtvvAxGA8Hd": "Year Company Founded", // What year was the company founded?
        "ktNAmVGq5jKV6k251MMHhD": "Additional Notes (Optional)", // Employer Identification Number
        "2x1P8FVrLaSZ1h1yzctQvx": "NAICS Code", // NAICS Code
        "7t7nvwF28RQd41VAFhaCMt": "SIC Code", // SIC Code
        "u7W18HRWFJJ22qWJYYTuan": "Additional Notes (Optional)", // What is the company's full legal name?
        "j8L1XKc1djZL3i5mE7Bge8": "Additional Notes (Optional)", // What is the Entity Type?
        "anHLFS6Z1uLM2rMQr4Np5z": "Additional Notes (Optional)", // What is the Tax Structure?
        "wC3xSLzj1HqzdPm9ZU4Gos": "State of Formation", // Entity state of formation
        "1XEj9M5RRREzjgNfdP46v8": "Additional Notes (Optional)", // Is the company a part of any of the following?
        "tc11o2pXix7LFcKCHv73o3": "Additional Notes (Optional)", // Non-Disclosure Agreement (NDA) (Optional)
        "rJ7KPfPiTjwvpPK9YdWkSo": "Additional Notes (Optional)", // Will you be the signer for the NDA?
        "9agS7ZVuek3K1YhT7f6TyG": "Alternate NDA Signer Name", // NDA Signer's Name
        "kiKmv6AT4S7842grdM5QMf": "Alternate NDA Signer Title", // NDA Signer's Title
        "fwBf6556E6eGzDRKPY14Qt": "Alternate NDA Signer Email", // NDA Signer's Email
        "qMhssvjAnuUkCEnqFUPoTf": "Additional Notes (Optional)", // How many benefit-eligible US Employees does the company have?
        "6418z3aAymx24EFgBfFvRZ": "Additional Notes (Optional)", // Est. of benefit-eligible EEs
        "oY8abhP2ZU5yLx7XXjek5P": "Additional Notes (Optional)", // Est. of medical enrolled EEs
        "k42qWo25NC8SQAbqsdXJTw": "Additional Notes (Optional)", // Expected growth in headcount in next 12 months
        "qoamzTPFTTcXEpVPaeWNxp": "Additional Notes (Optional)", // Upload Plan Summaries and/or Benefits Guide
        "4D4KESQWyCbMd9GMV6vfV4": "Audit Invoices", // Upload Invoices
        "jT6qXPuoVu8BJR9jCg3SoM": "Census Upload", // Upload Employee Census
        "amq634HFjRt7coRWphEtv9": "Additional Notes (Optional)", // Is there anything else you would like us to know about your benefits package?
        "pVCAB4Pq4eUTce8abZG6d1": "Benefits (In Your Own Words)", // Benefits I.Y.O.W. (In Your Own Words)
        "oCxH5wyvd6VQumDmBYV7B5": "How Do You Currently Offer Medical Benefits?", // Which of these benefits do you currently offer to your employess?
        "aMcN4nXFrtgT7bLbu6SbcW": "Additional Notes (Optional)", // Do you plan to add any of these benefits at this time?
        "kbrDFTxExGMQo9D5jKfRjP": "Additional Notes (Optional)", // What are your major benefit pain points?
        "1fwdKjH8VX2LutJbgcN8Fa": "Additional Notes (Optional)", // Please choose a few ways that would interest you to reinvest potential savings f
        "rnM4BUDwQiBHbzZtyFkC7p": "Additional Notes (Optional)", // Insurance Renewal of Medical Coverage
        "tLV9stuQyKYbS9yWupHWmj": "Additional Notes (Optional)", // How is your medical plan currently structured?
        "jjZUuwKnQ1UUbNpdLNXcoG": "Additional Notes (Optional)", // When was the last time you reviewed rates and carriers for all ancillary lines o
        "dBV1NufgXWbrBn4XWmTWL3": "Additional Notes (Optional)", // What is your experience with your dental network?
        "25gf7WsHx49DjfaHYkWsFG": "Additional Notes (Optional)", // For a dental policy what sounds more reasonable?
        "u55FunQd2AWHpUzRtNAZJF": "Additional Notes (Optional)", // What are your opinions on covering orthodontics?
        "cnx4R9CRhZuavdJNFbqbCK": "Additional Notes (Optional)", // Experience with vision plan??
        "8GxxungxB7Q59ErBFzkutN": "Additional Notes (Optional)", // What is your general stance toward employees submitting individual health questi
        "nZ6QUUNsBUH99q1RVXxW1G": "Additional Notes (Optional)", // What is your opinion on gathering employee feedback on the benefit package (Puls
        "5iKwoYUptm69D3khNSJVjZ": "Additional Notes (Optional)", // In your opinion, what is the ideal number of medical plan options you would like
        "7n2yJ85FSQLa4uUZvrjb1L": "Additional Notes (Optional)", // Which of the following plan types do you think you would like to offer?
        "82rzWzk8WTkEDS1EkBtjs2": "Additional Notes (Optional)", // Total Cost (In choosing a carrier and plans, how important are the following?)
        "crTWqp2vrmPcqKzpwZEuyu": "Additional Notes (Optional)", // Size of Network (In choosing a carrier and plans, how important are the followin
        "bimynMrLcvV614RS8DnM1V": "Additional Notes (Optional)", // Telemedicine Access (In choosing a carrier and plans, how important are the foll
        "wokvBiUfzsLwas5o9da1qY": "Additional Notes (Optional)", // User Experience (In choosing a carrier and plans, how important are the followin
        "3NjFMJ8oY3gd9iYpXVJM3N": "Additional Notes (Optional)", // Value for Money (In choosing a carrier and plans, how important are the followin
        "2JBDdYybcpdnFu73cmu1Ds": "Additional Notes (Optional)", // Biggest Name / Market Share (In choosing a carrier and plans, how important are 
        "6PugrAK6EjFdV4UvmWYufV": "Additional Notes (Optional)", // Mental Health Resources (In choosing a carrier and plans, how important are the 
        "nBxJFrAS1HeB7mMJgGXJn8": "Additional Notes (Optional)", // Modern Technology (In choosing a carrier and plans, how important are the follow
        "s5xupYk5QpAFYT5SYUvVdX": "Additional Notes (Optional)", // Which of the following does your workforce include?
        "fsW37DZtfebmK1MpwToXaE": "Additional Notes (Optional)", // How many hours per week are required for benefit eligibility?
        "vgkKdxQLTQgaKJeAa27vEh": "Additional Notes (Optional)", // Are all benefit eligible employees treated the same or do different classes exis
        "tuiVTF5BjuCgC7eHu2mV98": "Classes Exist For", // Classes exist for the following?
        "492951F98U8RVmo6C9Ni3F": "Additional Notes (Optional)", // Do you want domestic partners to be eligible for benefits?
        "caqYeZTuxhXLLPNFt5hA1r": "Additional Notes (Optional)", // What is your most common benefit waiting period?
        "eDKFSsLdbKPueK5JWqJM1A": "Additional Notes (Optional)", // When do benefits enrollments become effective?
        "ek88piYngfK767pv4WsVsS": "Predominant Payroll Frequency", // What is your predominant payroll frequency?
        "fH8MJgMUjDNwTZh21NDivU": "Additional Notes (Optional)", // Do all benefit-eligible employees get paid on the same cycle?
        "ue5n2tw2GRAZQuyxpoUkEo": "Alternate Payroll Frequency", // Please select your alternate payroll frequency?
        "cw2kfLa8EYSDmxsLRrYNB9": "Additional Notes (Optional)", // How often are benefit deductions taken?
        "cf7aJQQ1ukFDMpPC5N2fV4": "Additional Notes (Optional)", // What frequency are benefit deductions taken?
        "tmti1tPR2DT58GgdKiHDaV": "Additional Notes (Optional)", // What is the employer Medical contribution strategy?
        "mwBcHregDXxzjBz68X7ZPe": "Dental EE %", // EE only (2)
        "vF2S9jFKtshrNiweU2LNCW": "Dental EE %", // EE + Spouse (5)
        "aD56FMfHDDwjijVy74L8Xt": "Additional Notes (Optional)", // EE + Child(ren) (1)
        "tXPbNbhz3VmqfobbYu62tS": "Dental EE %", // EE + Family (4)
        "6uoXnPTsrF9N3nWPkg3JUk": "Dental EE %", // EE only (1)
        "gZUrmnXJj6TmD2mwjt13Xi": "Dental EE %", // EE + Spouse (1)
        "2cF7GBiSfoVMERooGzT6XR": "Additional Notes (Optional)", // EE + Child(ren)
        "xxr5zepMzXs7n8MobfEaR3": "Dental EE %", // EE + Family (5)
        "us9cULgV4mazmYrQjxBSxa": "Additional Notes (Optional)", // Does this amount apply to a base plan and employees pay the difference to buy up
        "gko2mwmSTqXMTLr4wthFsu": "Additional Notes (Optional)", // What is the employer Dental contribution strategy?
        "pSxfFndC3VTjLDs6ua7g6U": "Dental EE %", // EE only (4)
        "3NWQM2LsY7b9edSHK5FNpt": "Dental EE %", // EE + Spouse
        "maYDxdNZkJEdELvSnXHCBq": "Additional Notes (Optional)", // EE + Child(ren) (4)
        "my7T69az2xKgfhjVvvrgfh": "Dental EE %", // EE + Family (3)
        "pXbv181uRG5fETxuxBi5fq": "Dental EE %", // EE only (5)
        "idFMRDFAbVn9aXwKTKY5z1": "Dental EE %", // EE + Spouse (2)
        "t3oMfWGndW3H7XTHaaKtir": "Additional Notes (Optional)", // EE + Child(ren) (5)
        "ds3kXf8U8NsHFpepQTWTAs": "Dental EE %", // EE + Family (1)
        "9qZFwhmsbhSBoLw4zzdXkT": "Additional Notes (Optional)", // What is the employer Vision contribution strategy?
        "nU67Kb6af3cSqMz88w8bxz": "Dental EE %", // EE only (3)
        "sZ2xzLfhi2npM9oAn2Asev": "Dental EE %", // EE + Spouse (3)
        "5kmVLf5WpxgLzAiWP1hjwd": "Dental EE %", // EE + Family
        "hSDhjQrh6MWLmeqtqhTWF9": "Additional Notes (Optional)", // EE + Child(ren) (3)
        "1Kegu1vwQjiwfDLugqb4ED": "Dental EE %", // EE only
        "ttvkfcoT5vyyGEWyzXtJNC": "Dental EE %", // EE + Spouse (4)
        "bDktZJUZqYBYAEoj9g9brP": "Additional Notes (Optional)", // EE + Child(ren) (2)
        "mD3uAHsuUGu2kB2Em4JvBe": "Dental EE %", // EE + Family (2)
        "4CENC2uJtW1KPRfXGLb2CX": "Currently with a PEO?", // Are you currently with a PEO?
        "tvHqVYFNwV9YYfM21MF6cf": "Additional Notes (Optional)", // Which PEO are you with?
        "dYwCF8mZuTXpPvpgC8FskQ": "Additional Notes (Optional)", // Which PEOs have you evaluated?
        "9FS6LprAAfh4wYUunrXgqf": "Additional Notes (Optional)", // Who is your payroll provider?
        "4CbhpKeUCYjrK9kYFYyyjn": "Additional Notes (Optional)", // Do you use any other HR software separate from your payroll?
        "deTtPbLxBW6YX3F6LcCuMn": "Additional Notes (Optional)", // Do you use An Employer of Record Service provider?
        "2fkt2ZLGA57cYej7JUjZYv": "Which EOR Do You Use?", // Which EOR provider do you currently use
        "xAZaHWjRm5vWDLjYdLSe1q": "Additional Notes (Optional)", // In which countries do you currently have multiple EOR employees?
        "stu29koX23zU7xnNccoBSJ": "Additional Notes (Optional)", // Is there anything else you would like us to know about your intended benefits pa
    },
    "jgaiJJZJvjus": {
        "gsvX": "Additional Notes (Optional)", // Type your question here
        "pc64": "Additional Notes (Optional)", // Please add or update premiums for each of your plans.
    },
    "jLwpyNvuB2us": {
        "3khn37NbHQYb7CN6NPgrx2": "Last Name", // Last Name
        "qYvbJrrJqLQjqQnVip6c3N": "First Name", // First Name
        "2d65uNNeKNqSmZT1k2WVRq": "Job Title", // Title
        "jZa7ip7oU533vM2qLWCkZj": "Phone Number", // Phone
        "ckkAfnKZoQag2Kqf7j71Cq": "Email", // Email
        "2UCyRd53bWrtdKXAK1XMy6": "Company Name", // Company Name
        "jMkzWAv3b9K5VCyGHPsZmw": "Estimated Benefit-Eligible Employees", // How many benefit-eligible US Employees does the company have?
        "a8LGYWqm6WhmN4ByM9TDHt": "Street Address", // What is your company address?
        "6eWgGjt7iTjtYcnZRfnCjm": "Entity Legal Name", // Legal name
        "r5Tp19xjoS2tMUaW63GCJB": "State of Formation", // State of Formation
        "aE23zBVWqLxxKfyZAacKm3": "Entity Type", // What is the Entity Type?
        "iez8bg63WnH294LzHwinHv": "Tax Structure", // What is the Tax Structure?
        "uTuDTocoypgCbQCkcHWUXN": "EIN", // Employer Identification Number (EIN)
        "hf2rRXr8RmGS1o5PFoFJJn": "SIC Code", // Preferred SIC Code
        "xfBVQncwKZoTzx4FDeHDLR": "NAICS Code", // Preferred NAICS Code
        "opsQwCsEVnschNufM581ph": "NDA Required", // Non-Disclosure Agreement (NDA) (Optional)
        "6jRhRnuZ2kzaWXQEYjccAQ": "Additional Notes (Optional)", // Will you be the signer for the NDA?
        "89C6yaJhUwD2hLhed5Pd9R": "Alternate NDA Signer Name", // NDA Signer's Name
        "52iYqLmZqi87WApC4ZUuM1": "Alternate NDA Signer Title", // NDA Signer's Title
        "uJTQWkaMyr8daPGbwKfGJt": "Alternate NDA Signer Email", // NDA Signer's Email
        "kTefLrKMYMqFgSnTi2sruD": "Expected Start Month", // Expected Benefit Start Month
        "5rTpWrNmhXK7vpf5HrWiTf": "Currently with a PEO?", // Are you currently with a PEO?
        "vEu5E6WSrh7hr6vNnLtcYc": "Current PEO", // What PEO are you working with?
        "chZqidnnuADLqDMMhKU6JC": "Evaluated PEOs", // What PEOs have you evaluated?
        "odWtJEgDwD2FP72y1hSZAG": "Payroll Provider", // Who is your payroll provider?
        "dyTDunFBzPwYaJ6y1HUNmu": "Additional Notes (Optional)", // What is your general stance toward employees submitting individual health questi
        "jAdrKd4eMWZ2RxiSqKqJK2": "Additional Notes (Optional)", // In your opinion, what is the ideal number of medical plan options you would like
        "6TGDTAjUbJ2pcw6xNBoXWd": "Additional Notes (Optional)", // Which of the following plan types do you think you would like to offer?
        "7qZbS9oj1TSCcUPCiRbDga": "Additional Notes (Optional)", // Total Cost (In choosing a carrier and plans, how important are the following?)
        "1ftkyHoFU66FJYwum7ZHXj": "Additional Notes (Optional)", // Size of Network (In choosing a carrier and plans, how important are the followin
        "ah4qcTmAA8yidznBt5gvha": "Additional Notes (Optional)", // Telemedicine Access (In choosing a carrier and plans, how important are the foll
        "kGQtKVPzWUAszgoSkMsP68": "Additional Notes (Optional)", // User Experience (In choosing a carrier and plans, how important are the followin
        "xcB3nRWdcykviaf5aJnoLN": "Additional Notes (Optional)", // Value for Money (In choosing a carrier and plans, how important are the followin
        "tyNhTBMd1Jw3cUBsyq7Jho": "Additional Notes (Optional)", // Biggest Name / Market Share (In choosing a carrier and plans, how important are 
        "1NP2Vxs9EN6WS72ubMa4uD": "Additional Notes (Optional)", // Mental Health Resources (In choosing a carrier and plans, how important are the 
        "vdhdk1c2U6qRgFMfbEgrbC": "Additional Notes (Optional)", // Modern Technology (In choosing a carrier and plans, how important are the follow
        "oG5d1sEYyqicGUJFT6qvPr": "Additional Notes (Optional)", // What benefits do you plan to offer at this time?
        "6NfiwHmKWDbUkaMzAAJC26": "Additional Notes (Optional)", // What contribution strategy do you have in mind?
        "whhcQxhxkMZRwZJYfVQRRD": "Additional Notes (Optional)", // Is there anything else you would like us to know about your benefits package?
        "p77mtNXwXoYsAT1H1z87iP": "Benefits (In Your Own Words)", // Benefits I.Y.O.W. (In Your Own Words)
    },
    "eQ7FVU76PDus": {
        "kGqMobiUDPcHQXPEsEWGhs": "Company", // Company
        "bNkoRCS16B1NF8Vu3Kz9JR": "Benefit Year", // Benefit Year
        "9xm1AdHoV7ZErSGuemYwT3": "Medical Tier", // How are you currently enrolled for health benefits?
        "9rvPU3rfdvaY6355Si6DTP": "Medical Tier", // On which medical plan are you enrolled?
        "1tTsT4b7YxSrc2e8bTQtMD": "Overall", // Overall Benefits Package
        "eVZknTJzZyJ8XMoKqUeVFW": "Medical Options", // Medical Plan Options
        "4UCLbaHFiRB9ARDkPVvqDd": "Medical Network", // Medical Network
        "gEoRfJNxN37JVkvyow4NWU": "Employee Name", // Employee Costs
        "qgw9BnxZsRS2b3oc5iH5ej": "Non-Medical", // Other Benefits (Non-Medical)
        "6EbFGLKbaNEhDbn4FyCD2J": "Comments", // Comments
        "8w6e": "Comments", // Type your question here
    },
    "aTDkqH7zTmus": {
        "jFiU": "Document type test", // Document Type
        "kZ8Y": "Additional Notes (Optional)", // To make sure everything is processed correctly, please upload one document at a 
        "mG7t": "Additional Notes (Optional)", // Groupkey
    },
    "eBxXtLZdK4us": {
        "khqL": "Group_ID", // Group Data Record ID
        "3khn37NbHQYb7CN6NPgrx2": "Last Name", // Last Name
        "qYvbJrrJqLQjqQnVip6c3N": "First Name", // First Name
        "2d65uNNeKNqSmZT1k2WVRq": "Job Title", // Title
        "jZa7ip7oU533vM2qLWCkZj": "Phone Number", // Phone
        "ckkAfnKZoQag2Kqf7j71Cq": "Work Email", // Email
        "2UCyRd53bWrtdKXAK1XMy6": "Company Name", // Company Name
        "ayXo": "Street Address", // Address
        "fT94": "City", // City
        "hmTa": "State / Province", // State / Province
        "wLev": "ZIP Code", // ZIP Code
        "r1TkXLw3QBZBCkoRHidEPs": "Year Company Founded", // Year company founded
        "uTuDTocoypgCbQCkcHWUXN": "EIN", // Employer Identification Number (EIN)
        "hf2rRXr8RmGS1o5PFoFJJn": "SIC Code", // Preferred SIC Code
        "xfBVQncwKZoTzx4FDeHDLR": "NAICS Code", // Preferred NAICS Code
        "jMkzWAv3b9K5VCyGHPsZmw": "Additional Notes (Optional)", // How many benefit-eligible US employees does the company have?
        "87fD37dczxpgzodHMWgvWT": "Estimated Medical-Enrolled Employees", // Estimated Medical Enrolled EEs
        "onbhhvHYbup9VUBE6eAAaz": "Estimated Benefit-Eligible Employees", // Estimated Benefit Eligible EEs
        "xcqpaj6Sfv98YJFAUiCZ4z": "Expected Headcount Growth", // Expected Headcount Growth (next 12 months)
        "opsQwCsEVnschNufM581ph": "NDA Required", // Would you like Betafits to sign an NDA regarding your company and employee infor
        "6eWgGjt7iTjtYcnZRfnCjm": "Additional Notes (Optional)", // What is the full legal name of the company?
        "4eLaFN3YpBRxS1gqEFhqG8": "State of Formation", // State of formation
        "aE23zBVWqLxxKfyZAacKm3": "Entity Type", // Entity type
        "6jRhRnuZ2kzaWXQEYjccAQ": "Additional Notes (Optional)", // Will you be the signer for the NDA?
        "52iYqLmZqi87WApC4ZUuM1": "Alternate NDA Signer Title", // NDA Signer's Title
        "89C6yaJhUwD2hLhed5Pd9R": "Alternate NDA Signer Name", // NDA Signer's Name
        "uJTQWkaMyr8daPGbwKfGJt": "Alternate NDA Signer Email", // NDA Signer's Email
        "d4wVEowxCpRtdsXr81nFnF": "Additional Notes (Optional)", // Which of the following benefits do you offer at this time?
        "iHxYYn5HYHDvKGH7Ec9Z5L": "Current Start Month", // Renewal month of medical coverage
        "gSmJUwa363oWH5x2Q68ojZ": "Expected Start Month", // Desired effective date for quotes (if different than renewal)
        "62Sic2EiCFMVuxwFUM9L1k": "How Do You Currently Offer Medical Benefits?", // How do you currently offer medical benefits?
        "7XiD4e9FAysNviYb9ocJQd": "Medical ER Contribution Strategy", // What is the medical contribution strategy?
        "hRA1LaWSMrrX2irz3r6XXd": "Please Describe Your Reason", // Please describe your contribution strategy?
        "aJ5QJvpDNyhXNMvoSmVEoT": "Additional Notes (Optional)", // Contribution to Dependents (% or $)
        "uaFGXRZwNyovwuXGKsCgDf": "Medical Employee Contribution (%)", // Contribution to Employee (% or $)
        "aByPiuEENQzRDaTFecMkKT": "Additional Notes (Optional)", // Does the percentage apply only the base plan? Employees pay the full cost to buy
        "b5zjBDR1YeKTq9GaVxQYWv": "Do You Currently Use An EOR?", // Do you currently use a PEO?
        "mM5ZyS9KeVz83eeqfdHoRn": "Current PEO", // Which PEO do you use?
        "vPgLS18szbAabJNGiwDnev": "Evaluated PEOs", // What PEOs have you evaluated?
        "kewbuyogJjkbbQNNXpbtxe": "HR Software Used", // Who is your payroll provider?
        "i5Cg": "Predominant Payroll Frequency", // What is your Payroll Frequency?
        "eKX8": "Deduction Frequency", // What is your Benefit Deduction Frequency?
        "1DzLVcVYD9X23eBWJguR2p": "Do Any of the Following Apply to Your Company or Benefits Package?", // Do any of the following apply to your company or benefits package?
        "iUedSGbFvtuwGorGfJLmoU": "Additional Notes (Optional)", // Please provide additional details for each selected option
        "hkZ8KcqU7mWUPnJK3WBybe": "Ideal Number of Medical Plan Options", // In your opinion, what is the ideal number of medical plan options you would like
        "qjLXquRvoppwrWfFrFNEnf": "Expected Plan Types", // Which of the following plan types do you think you would like to offer?
        "p5mVMXPLaNV9YFDKZNT5Ri": "Additional Notes (Optional)", // Total Cost (In choosing a carrier and plans, how important are the following?)
        "uL9yj4Rhe57QLkjzEufduF": "Additional Notes (Optional)", // Value for Money (In choosing a carrier and plans, how important are the followin
        "csQPgeHyH4ZAuCF4f7h8zR": "Additional Notes (Optional)", // Carrier Name/Market Share (In choosing a carrier and plans, how important are th
        "eXnR1VZdpgJmCGCR3YgWWs": "Additional Notes (Optional)", // Size of Network (In choosing a carrier and plans, how important are the followin
        "vfwAxLwvZ6VrLCp9uWz5wU": "Additional Notes (Optional)", // Healthcare Navigation (In choosing a carrier and plans, how important are the fo
        "ptwJD4iPVBvA92FSgMPaA9": "Additional Notes (Optional)", // Mental Health Resources (In choosing a carrier and plans, how important are the 
        "8bKqEjRKcZQMEAYZWGNwjZ": "Additional Notes (Optional)", // Telemedicine Access (In choosing a carrier and plans, how important are the foll
        "qAYFpWoy3ZHXcP968p3uh5": "Additional Notes (Optional)", // Modern Technology and Support (In choosing a carrier and plans, how important ar
        "qLpBxT2RxYU81MgD6Qb48P": "Do Any of the Following Apply to Your Company or Benefits Package?", // Which of the following are notable benefits pain points for your company?
        "pmcR22jTVUgcBSXBKQGMJq": "Additional Notes (Optional)", // Which best describes your openness toward employees submitting individual health
        "awX85gzf6ywgCQsnu1HAKr": "Additional Notes (Optional)", // Would you like to gather employee feedback for benchmarking and improving your b
        "5gwf": "Additional Notes (Optional)", // To upload a document, click the + Upload button below.
        "8xGZP1oCmeWgPa2GhFquPc": "Benefits (In Your Own Words)", // Benefits I.Y.O.W. (In Your Own Words)
        "tP2QxuesGXQswTM8r8LNeV": "Additional Notes (Optional)", // Is there anything else you would like us to know about your benefits package?
    },
    "urHF8xDu7eus": {
        "iuLc": "Type of Broker", // What type of broker, platform, or consultant supports your employee benefits?
        "q7SL": "Broker Service Agreement?", // Do you have a signed service agreement or only a Broker of Record (BOR) letter?
        "1BQA": "Broker Fees", // Do you pay your broker any fees beyond commissions or standard premiums?
        "kFtK": "Broker Subsidize Cost?", // Does your broker currently pay for or subsidize any of the following services?
        "ucXn": "Broker Contact Frequency", // How often do you contact your broker for support?
        "oXHq": "Broker Meet Frequency", // How often do you have strategic or renewal meetings with your broker?
        "17Hj": "Additional Notes (Optional)", // Which of the following services does your broker currently provide?
        "4vRz": "Additional Notes (Optional)", // How would you rate your broker’sresponsiveness and communication?
        "9Xgb": "Additional Notes (Optional)", // How would you rate your broker’srenewal strategy and plan benchmarking?
        "mDVP": "Additional Notes (Optional)", // How would you rate your broker’scompliance and documentation support?
        "6aHN": "Additional Notes (Optional)", // How would you rate your broker’sadmin coordination and day-to-day support?
        "1YiE": "Additional Notes (Optional)", // How would you rate your broker’svalue as a strategic partner?
        "aJXW": "Additional Notes (Optional)", // Please upload any broker documentation you have (e.g., signed service agreement 
    },
    "6eUGSndhtYus": {
        "4a93NzjYMKMaGEo9veT8pV": "NDA Required", // Non-Disclosure Agreement (NDA) (Optional)
        "akhj": "Group_ID", // Record ID
        "o19dKvYC9qGMfLEExpoXxf": "Entity Legal Name", // What is the company's full legal name?
        "fmJquAsRkqBxEpnwyZwd4L": "State of Formation", // What is the entity's state of formation?
        "wk639YhY1EEpuZgidtntGq": "Entity Type", // What is the entity type?
        "gAQ1ThdizsjffXvXeL1Yxv": "Additional Notes (Optional)", // Will you be the signer for the NDA?
        "aCC2cW2taXLxHpXPsYYYgm": "Alternate NDA Signer Name", // Name of the NDA Signer
        "teMNcdpmdLWx1psKKqHPV2": "Alternate NDA Signer Title", // Title of the NDA Signer
        "7LD9hA4LaXHZqNYkJ64Gqg": "Alternate NDA Signer Email", // Email of the NDA Signer
        "gQJ57d5ZjWPfej6teQoUuR": "Entity Legal Name", // What is the Legal Name of the Entity?
        "qRv5QPb1PJ2EZ7QYMx5c6A": "Additional Notes (Optional)", // Entity Type (Corporation, LLC, etc.)
        "4DekuksCczyoSV6gDQ3ATv": "Additional Notes (Optional)", // What is the Entity State of Formation?
        "ccywgV1PQBZqeF8q5VxCkn": "Additional Notes (Optional)", // Employer Identification Number
        "qXwNuDfp6PMfG1GZfAuTmV": "Additional Notes (Optional)", // Expected Benefit Start Month or Renewal of Medical Coverage
    },
};

export const FILLOUT_QUESTION_ID_TO_LABEL: Record<string, Record<string, string>> = {
    "199DTBMrsLus": {
        "4yptyRTf1voVY7sdFoJxGv": "First Name",
        "vkabBeFF6JFQzMgZ4GNPVy": "Last Name",
        "qUc44oHzKFJSS5mxgHjNSL": "Date of Birth",
        "vYP5rMTAgx4DPKvh4NMn9G": "Relation",
        "qAuXdq5iYpxy1Bp9jMaDWm": "Gender",
    },
    "tE2Bb3x71Cus": {
        "e4WD": "Company Name:",
        "dg99": "FEIN:",
        "6YEsahAjzemmBLvBiGPqbQ": "Phone:",
        "8C36dGtSafJkQFyMdoLotN": "DBA:",
        "9rTDWeYHDLuqiEk4XSs6P9": "Website:",
        "hJ3ns8x5QG2C1kT58SFreu": "Email:",
        "j1eccjcascjGZWLtiE1XdR": "Fax:",
        "q6xnmgZcKpTjnagzBbzNAb": "Physical Address:",
        "8FAo": "State",
        "3LFSMi2bB9nZMSYLLJuDDH": "City:",
        "igvd3ZJvAhYzQF79Tg2Ubk": "Zip: (1)",
        "aQ71": "Is your mailing address the same as your physical address?",
        "kRymjtG7VKcDcmK7hmKx2n": "Mailing Address:",
        "n61j": "State (1)",
        "gjZtdpppkNMkaFNykaMRxa": "City: (1)",
        "eeTZrLNZJhsiwfqKSWk8sn": "Zip:",
        "76op": "Detailed Description of Operations:",
        "mzyA": "Do your employees handle any type of product, prototypes, machinery, tools, etc?",
        "vF2Z": "What kind of equipment is used?",
        "8snnXeauHTjC4XhcZwftvY": "What state are you incorporated in?",
        "2p7j": "In Business Since (YYYY):",
        "9xDj": "NAICS Code",
        "cAdG": "SIC Code:",
        "56UB": "Do other entities use this FEIN?",
        "n2QMrYmMsQDrjiihVWDjsr": "Additional Company Name",
        "adA8": "Entity Type",
        "3QJW": "Hours of Operation:",
        "gaVf": "Pay Frequency:",
        "jReW": "Current Payroll Provider:",
        "usAh": "Completed and signed RFP (Request for Proposal).",
        "h9bq": "Current Payroll Report with deductions and YTD wages.• Report should identify state, workers’ compensation class code, and annual wages",
        "jLui": "Workers’ Compensation Policy Declaration Page if available.• If currently with a PEO, please provide most recent premium billing statement, or a report detailing payroll by class code and state",
        "ryVS": "Three to five-year loss runs (valued within last 45-days).• If company has been in business less than three years, or no workers’ compensation experience,• Claims in excess of $25,000, require nature and detail of those claims.",
    },
    "xn4WCJ9D8pus": {
        "vATB": "Company Name",
        "2uHd": "Link to Users",
        "jf4z": "Link to Assigned Forms",
        "rT74": "Document Type",
        "vr6K": "Upload New Group Document",
        "ewYV": "Upload Group's Document",
    },
    "fYJ3MNj7VQus": {
        "pmLe": "How are benefit carrier updates managed and who is responsible for submitting them?",
        "gT66": "Please specify (7)",
        "sYyR": "How are payroll deduction changes managed and who is responsible for completing them?",
        "313V": "Please specify (6)",
        "4vFw": "How do you perform enrollment and deduction audits (e.g., confirming employees are properly enrolled and deductions are accurate)?",
        "iPzP": "Please specify (8)",
        "s5oB": "How frequently do you audit enrollments?",
        "nSQt": "How frequently do you audit payroll deductions?",
        "qMuK": "How is your benefits guide shared with employees?",
        "46Ef": "Who creates or updates your benefit guide?",
        "bgfx": "Please specify",
        "fNU6": "What type of email communication is sent to new hires about their benefits?",
        "5BXX": "When are benefits instructions typically sent to new hires?",
        "pdzn": "How do you deliver benefits orientation to new hires?",
        "r6UB": "Who leads the benefits discussions with new hires?",
        "2j3P": "How long does your Open Enrollment period typically run?",
        "2ATs": "Please specify (1)",
        "pr7f": "What type of Open Enrollment process do you use?",
        "mfsT": "Who sets up Open Enrollment in your benefits administration system?",
        "jgkY": "Please specify (3)",
        "g7ty": "What kind of benefits education/support do you provide during Open Enrollment?",
        "4Nnj": "Please specify (2)",
        "nVUN": "Who leads these employee meetings or communications?",
        "uJKk": "Who handles COBRA or state continuation administration?",
        "59qg": "Please specify (4)",
        "ocYq": "How do you notify COBRA-eligible employees about continuation coverage?",
        "i7kn": "Which tax-advantaged benefits do you currently offer?",
        "7FBG": "How does the employer contribute to the HSA?",
        "tV7o": "Type your question here",
        "dCnf": "How are HSA contributions administered?",
        "apAq": "Please specify (5)",
        "58p8": "How is the HSA contribution funded?",
        "3rkc": "How do employees open or access their HSA account?",
    },
    "ujTSx72pr5us": {
        "fpKM": "How would you describe the level of compliance support you currently receive from your broker or vendors?",
        "svnT": "What systems or methods are used to track your compliance-related tasks throughout the year?",
        "wVUD": "What are your primary sources for staying informed about benefits compliance requirements?",
        "dc3Q": "Who manages your ERISA Wrap Document and ensures it is updated?",
        "1nxi": "How is your Section 125 (Premium Only Plan) Document prepared and kept current?",
        "9MSF": "How is your Health & Welfare Form 5500 prepared and filed?",
        "vHX9": "Who prepares and files your ACA Forms 1094/1095?",
        "1J9u": "Is the cost of employer-sponsored healthcare coverage reported on employees W-2s (Box 12 DD)?",
        "4K16": "How are required annual notices delivered to employees?",
        "6vNE": "Do you conduct annual non-discrimination testing for your Health & Welfare plans?",
        "fMAe": "How is annual non-discrimination testing for your Health & Welfare plans handled?",
        "mbNe": "1095-B Reporting (How are the following compliance requirements currently handled?)",
        "hTTa": "PCORI Filing (How are the following compliance requirements currently handled?)",
        "tcDK": "RxDC Reporting (How are the following compliance requirements currently handled?)",
        "uVBo": "State-Mandated Benefits Reporting (How are the following compliance requirements currently handled?)",
        "vZ8p": "How do you manage compliance with Paid Leave and other employment-related laws across multiple states?",
        "nbY1": "What systems or partners help you track and administer leave laws?",
    },
    "cqBbC1vEUcus": {
        "e29p": "Do you currently use a PEO?",
        "tY3h": "What were the main reasons you decided not to use a PEO?",
        "w4Xq": "Which PEO do you use?",
        "pt6E": "Would you be open to switching to another PEO or to a payroll-only solution?",
        "bjGS": "Which PEOs have you evaluated?",
        "bPLT": "What are your top considerations when exploring a PEO?",
        "okAk": "Do you currently use an EOR?",
        "tyXd": "EOR Vendors You’ve Used",
        "oswx": "Specify other vendor(s)",
        "4UzM": "EOR Countries & Workforce Details",
        "a5L8": "Upload current PEO Invoice",
        "jZzH": "Upload current EOR Invoice",
        "84QH": "Other details you’d like us to know",
    },
    "wpjffs7r5pus": {
        "jLdKiy15wgdtyZUB4Jc38T": "What is your last name?",
        "kXUEyWx9AWYbgBQw2Q9sqe": "What is your first name?",
        "8jrHZDeqnveRgrG2xjowcs": "What is your title at the company?",
        "rEWF5qRCMZqWe5vzVx496A": "What is your work email?",
        "sJWdmf7r4raFsLfcpjXiWe": "What is the company name?",
        "rPuGVUBax3DqZvKHqWR4Kj": "What is the company address?",
        "dMx5cR3qTJQLvxaYHvzVFE": "Do you have physical locations or active business addresses in any other state(s)?",
        "b64eD9aKCVwXSnx6yFBN4c": "In which other state(s)?",
        "2XLfhSsc8T8wtvvAxGA8Hd": "What year was the company founded?",
        "ktNAmVGq5jKV6k251MMHhD": "Employer Identification Number",
        "2x1P8FVrLaSZ1h1yzctQvx": "NAICS Code",
        "7t7nvwF28RQd41VAFhaCMt": "SIC Code",
        "u7W18HRWFJJ22qWJYYTuan": "What is the company's full legal name?",
        "j8L1XKc1djZL3i5mE7Bge8": "What is the Entity Type?",
        "anHLFS6Z1uLM2rMQr4Np5z": "What is the Tax Structure?",
        "wC3xSLzj1HqzdPm9ZU4Gos": "Entity state of formation",
        "1XEj9M5RRREzjgNfdP46v8": "Is the company a part of any of the following?",
        "tc11o2pXix7LFcKCHv73o3": "Non-Disclosure Agreement (NDA) (Optional)",
        "rJ7KPfPiTjwvpPK9YdWkSo": "Will you be the signer for the NDA?",
        "9agS7ZVuek3K1YhT7f6TyG": "NDA Signer's Name",
        "kiKmv6AT4S7842grdM5QMf": "NDA Signer's Title",
        "fwBf6556E6eGzDRKPY14Qt": "NDA Signer's Email",
        "qMhssvjAnuUkCEnqFUPoTf": "How many benefit-eligible US Employees does the company have?",
        "6418z3aAymx24EFgBfFvRZ": "Est. of benefit-eligible EEs",
        "oY8abhP2ZU5yLx7XXjek5P": "Est. of medical enrolled EEs",
        "k42qWo25NC8SQAbqsdXJTw": "Expected growth in headcount in next 12 months",
        "qoamzTPFTTcXEpVPaeWNxp": "Upload Plan Summaries and/or Benefits Guide",
        "4D4KESQWyCbMd9GMV6vfV4": "Upload Invoices",
        "jT6qXPuoVu8BJR9jCg3SoM": "Upload Employee Census",
        "amq634HFjRt7coRWphEtv9": "Is there anything else you would like us to know about your benefits package?",
        "pVCAB4Pq4eUTce8abZG6d1": "Benefits I.Y.O.W. (In Your Own Words)",
        "oCxH5wyvd6VQumDmBYV7B5": "Which of these benefits do you currently offer to your employess?",
        "aMcN4nXFrtgT7bLbu6SbcW": "Do you plan to add any of these benefits at this time?",
        "kbrDFTxExGMQo9D5jKfRjP": "What are your major benefit pain points?",
        "1fwdKjH8VX2LutJbgcN8Fa": "Please choose a few ways that would interest you to reinvest potential savings from your benefit costs",
        "rnM4BUDwQiBHbzZtyFkC7p": "Insurance Renewal of Medical Coverage",
        "tLV9stuQyKYbS9yWupHWmj": "How is your medical plan currently structured?",
        "jjZUuwKnQ1UUbNpdLNXcoG": "When was the last time you reviewed rates and carriers for all ancillary lines of coverage?",
        "dBV1NufgXWbrBn4XWmTWL3": "What is your experience with your dental network?",
        "25gf7WsHx49DjfaHYkWsFG": "For a dental policy what sounds more reasonable?",
        "u55FunQd2AWHpUzRtNAZJF": "What are your opinions on covering orthodontics?",
        "cnx4R9CRhZuavdJNFbqbCK": "Experience with vision plan??",
        "8GxxungxB7Q59ErBFzkutN": "What is your general stance toward employees submitting individual health questionnaires to have access to certain health insurance options?",
        "nZ6QUUNsBUH99q1RVXxW1G": "What is your opinion on gathering employee feedback on the benefit package (Pulse survey)",
        "5iKwoYUptm69D3khNSJVjZ": "In your opinion, what is the ideal number of medical plan options you would like to offer?",
        "7n2yJ85FSQLa4uUZvrjb1L": "Which of the following plan types do you think you would like to offer?",
        "82rzWzk8WTkEDS1EkBtjs2": "Total Cost (In choosing a carrier and plans, how important are the following?)",
        "crTWqp2vrmPcqKzpwZEuyu": "Size of Network (In choosing a carrier and plans, how important are the following?)",
        "bimynMrLcvV614RS8DnM1V": "Telemedicine Access (In choosing a carrier and plans, how important are the following?)",
        "wokvBiUfzsLwas5o9da1qY": "User Experience (In choosing a carrier and plans, how important are the following?)",
        "3NjFMJ8oY3gd9iYpXVJM3N": "Value for Money (In choosing a carrier and plans, how important are the following?)",
        "2JBDdYybcpdnFu73cmu1Ds": "Biggest Name / Market Share (In choosing a carrier and plans, how important are the following?)",
        "6PugrAK6EjFdV4UvmWYufV": "Mental Health Resources (In choosing a carrier and plans, how important are the following?)",
        "nBxJFrAS1HeB7mMJgGXJn8": "Modern Technology (In choosing a carrier and plans, how important are the following?)",
        "s5xupYk5QpAFYT5SYUvVdX": "Which of the following does your workforce include?",
        "fsW37DZtfebmK1MpwToXaE": "How many hours per week are required for benefit eligibility?",
        "vgkKdxQLTQgaKJeAa27vEh": "Are all benefit eligible employees treated the same or do different classes exist?",
        "tuiVTF5BjuCgC7eHu2mV98": "Classes exist for the following?",
        "492951F98U8RVmo6C9Ni3F": "Do you want domestic partners to be eligible for benefits?",
        "caqYeZTuxhXLLPNFt5hA1r": "What is your most common benefit waiting period?",
        "eDKFSsLdbKPueK5JWqJM1A": "When do benefits enrollments become effective?",
        "ek88piYngfK767pv4WsVsS": "What is your predominant payroll frequency?",
        "fH8MJgMUjDNwTZh21NDivU": "Do all benefit-eligible employees get paid on the same cycle?",
        "ue5n2tw2GRAZQuyxpoUkEo": "Please select your alternate payroll frequency?",
        "cw2kfLa8EYSDmxsLRrYNB9": "How often are benefit deductions taken?",
        "cf7aJQQ1ukFDMpPC5N2fV4": "What frequency are benefit deductions taken?",
        "tmti1tPR2DT58GgdKiHDaV": "What is the employer Medical contribution strategy?",
        "mwBcHregDXxzjBz68X7ZPe": "EE only (2)",
        "vF2S9jFKtshrNiweU2LNCW": "EE + Spouse (5)",
        "aD56FMfHDDwjijVy74L8Xt": "EE + Child(ren) (1)",
        "tXPbNbhz3VmqfobbYu62tS": "EE + Family (4)",
        "6uoXnPTsrF9N3nWPkg3JUk": "EE only (1)",
        "gZUrmnXJj6TmD2mwjt13Xi": "EE + Spouse (1)",
        "2cF7GBiSfoVMERooGzT6XR": "EE + Child(ren)",
        "xxr5zepMzXs7n8MobfEaR3": "EE + Family (5)",
        "us9cULgV4mazmYrQjxBSxa": "Does this amount apply to a base plan and employees pay the difference to buy up?",
        "gko2mwmSTqXMTLr4wthFsu": "What is the employer Dental contribution strategy?",
        "pSxfFndC3VTjLDs6ua7g6U": "EE only (4)",
        "3NWQM2LsY7b9edSHK5FNpt": "EE + Spouse",
        "maYDxdNZkJEdELvSnXHCBq": "EE + Child(ren) (4)",
        "my7T69az2xKgfhjVvvrgfh": "EE + Family (3)",
        "pXbv181uRG5fETxuxBi5fq": "EE only (5)",
        "idFMRDFAbVn9aXwKTKY5z1": "EE + Spouse (2)",
        "t3oMfWGndW3H7XTHaaKtir": "EE + Child(ren) (5)",
        "ds3kXf8U8NsHFpepQTWTAs": "EE + Family (1)",
        "9qZFwhmsbhSBoLw4zzdXkT": "What is the employer Vision contribution strategy?",
        "nU67Kb6af3cSqMz88w8bxz": "EE only (3)",
        "sZ2xzLfhi2npM9oAn2Asev": "EE + Spouse (3)",
        "5kmVLf5WpxgLzAiWP1hjwd": "EE + Family",
        "hSDhjQrh6MWLmeqtqhTWF9": "EE + Child(ren) (3)",
        "1Kegu1vwQjiwfDLugqb4ED": "EE only",
        "ttvkfcoT5vyyGEWyzXtJNC": "EE + Spouse (4)",
        "bDktZJUZqYBYAEoj9g9brP": "EE + Child(ren) (2)",
        "mD3uAHsuUGu2kB2Em4JvBe": "EE + Family (2)",
        "4CENC2uJtW1KPRfXGLb2CX": "Are you currently with a PEO?",
        "tvHqVYFNwV9YYfM21MF6cf": "Which PEO are you with?",
        "dYwCF8mZuTXpPvpgC8FskQ": "Which PEOs have you evaluated?",
        "9FS6LprAAfh4wYUunrXgqf": "Who is your payroll provider?",
        "4CbhpKeUCYjrK9kYFYyyjn": "Do you use any other HR software separate from your payroll?",
        "deTtPbLxBW6YX3F6LcCuMn": "Do you use An Employer of Record Service provider?",
        "2fkt2ZLGA57cYej7JUjZYv": "Which EOR provider do you currently use",
        "xAZaHWjRm5vWDLjYdLSe1q": "In which countries do you currently have multiple EOR employees?",
        "stu29koX23zU7xnNccoBSJ": "Is there anything else you would like us to know about your intended benefits package?",
    },
    "jgaiJJZJvjus": {
        "gsvX": "Type your question here",
        "pc64": "Please add or update premiums for each of your plans.",
    },
    "jLwpyNvuB2us": {
        "3khn37NbHQYb7CN6NPgrx2": "Last Name",
        "qYvbJrrJqLQjqQnVip6c3N": "First Name",
        "2d65uNNeKNqSmZT1k2WVRq": "Title",
        "jZa7ip7oU533vM2qLWCkZj": "Phone",
        "ckkAfnKZoQag2Kqf7j71Cq": "Email",
        "2UCyRd53bWrtdKXAK1XMy6": "Company Name",
        "jMkzWAv3b9K5VCyGHPsZmw": "How many benefit-eligible US Employees does the company have?",
        "a8LGYWqm6WhmN4ByM9TDHt": "What is your company address?",
        "6eWgGjt7iTjtYcnZRfnCjm": "Legal name",
        "r5Tp19xjoS2tMUaW63GCJB": "State of Formation",
        "aE23zBVWqLxxKfyZAacKm3": "What is the Entity Type?",
        "iez8bg63WnH294LzHwinHv": "What is the Tax Structure?",
        "uTuDTocoypgCbQCkcHWUXN": "Employer Identification Number (EIN)",
        "hf2rRXr8RmGS1o5PFoFJJn": "Preferred SIC Code",
        "xfBVQncwKZoTzx4FDeHDLR": "Preferred NAICS Code",
        "opsQwCsEVnschNufM581ph": "Non-Disclosure Agreement (NDA) (Optional)",
        "6jRhRnuZ2kzaWXQEYjccAQ": "Will you be the signer for the NDA?",
        "89C6yaJhUwD2hLhed5Pd9R": "NDA Signer's Name",
        "52iYqLmZqi87WApC4ZUuM1": "NDA Signer's Title",
        "uJTQWkaMyr8daPGbwKfGJt": "NDA Signer's Email",
        "kTefLrKMYMqFgSnTi2sruD": "Expected Benefit Start Month",
        "5rTpWrNmhXK7vpf5HrWiTf": "Are you currently with a PEO?",
        "vEu5E6WSrh7hr6vNnLtcYc": "What PEO are you working with?",
        "chZqidnnuADLqDMMhKU6JC": "What PEOs have you evaluated?",
        "odWtJEgDwD2FP72y1hSZAG": "Who is your payroll provider?",
        "dyTDunFBzPwYaJ6y1HUNmu": "What is your general stance toward employees submitting individual health questionnaires?",
        "jAdrKd4eMWZ2RxiSqKqJK2": "In your opinion, what is the ideal number of medical plan options you would like to offer?",
        "6TGDTAjUbJ2pcw6xNBoXWd": "Which of the following plan types do you think you would like to offer?",
        "7qZbS9oj1TSCcUPCiRbDga": "Total Cost (In choosing a carrier and plans, how important are the following?)",
        "1ftkyHoFU66FJYwum7ZHXj": "Size of Network (In choosing a carrier and plans, how important are the following?)",
        "ah4qcTmAA8yidznBt5gvha": "Telemedicine Access (In choosing a carrier and plans, how important are the following?)",
        "kGQtKVPzWUAszgoSkMsP68": "User Experience (In choosing a carrier and plans, how important are the following?)",
        "xcB3nRWdcykviaf5aJnoLN": "Value for Money (In choosing a carrier and plans, how important are the following?)",
        "tyNhTBMd1Jw3cUBsyq7Jho": "Biggest Name / Market Share (In choosing a carrier and plans, how important are the following?)",
        "1NP2Vxs9EN6WS72ubMa4uD": "Mental Health Resources (In choosing a carrier and plans, how important are the following?)",
        "vdhdk1c2U6qRgFMfbEgrbC": "Modern Technology (In choosing a carrier and plans, how important are the following?)",
        "oG5d1sEYyqicGUJFT6qvPr": "What benefits do you plan to offer at this time?",
        "6NfiwHmKWDbUkaMzAAJC26": "What contribution strategy do you have in mind?",
        "whhcQxhxkMZRwZJYfVQRRD": "Is there anything else you would like us to know about your benefits package?",
        "p77mtNXwXoYsAT1H1z87iP": "Benefits I.Y.O.W. (In Your Own Words)",
    },
    "eQ7FVU76PDus": {
        "kGqMobiUDPcHQXPEsEWGhs": "Company",
        "bNkoRCS16B1NF8Vu3Kz9JR": "Benefit Year",
        "9xm1AdHoV7ZErSGuemYwT3": "How are you currently enrolled for health benefits?",
        "9rvPU3rfdvaY6355Si6DTP": "On which medical plan are you enrolled?",
        "1tTsT4b7YxSrc2e8bTQtMD": "Overall Benefits Package",
        "eVZknTJzZyJ8XMoKqUeVFW": "Medical Plan Options",
        "4UCLbaHFiRB9ARDkPVvqDd": "Medical Network",
        "gEoRfJNxN37JVkvyow4NWU": "Employee Costs",
        "qgw9BnxZsRS2b3oc5iH5ej": "Other Benefits (Non-Medical)",
        "6EbFGLKbaNEhDbn4FyCD2J": "Comments",
        "8w6e": "Type your question here",
    },
    "aTDkqH7zTmus": {
        "jFiU": "Document Type",
        "kZ8Y": "To make sure everything is processed correctly, please upload one document at a time.   You can submit additional documents right after",
        "mG7t": "Groupkey",
    },
    "eBxXtLZdK4us": {
        "khqL": "Group Data Record ID",
        "3khn37NbHQYb7CN6NPgrx2": "Last Name",
        "qYvbJrrJqLQjqQnVip6c3N": "First Name",
        "2d65uNNeKNqSmZT1k2WVRq": "Title",
        "jZa7ip7oU533vM2qLWCkZj": "Phone",
        "ckkAfnKZoQag2Kqf7j71Cq": "Email",
        "2UCyRd53bWrtdKXAK1XMy6": "Company Name",
        "ayXo": "Address",
        "fT94": "City",
        "hmTa": "State / Province",
        "wLev": "ZIP Code",
        "r1TkXLw3QBZBCkoRHidEPs": "Year company founded",
        "uTuDTocoypgCbQCkcHWUXN": "Employer Identification Number (EIN)",
        "hf2rRXr8RmGS1o5PFoFJJn": "Preferred SIC Code",
        "xfBVQncwKZoTzx4FDeHDLR": "Preferred NAICS Code",
        "jMkzWAv3b9K5VCyGHPsZmw": "How many benefit-eligible US employees does the company have?",
        "87fD37dczxpgzodHMWgvWT": "Estimated Medical Enrolled EEs",
        "onbhhvHYbup9VUBE6eAAaz": "Estimated Benefit Eligible EEs",
        "xcqpaj6Sfv98YJFAUiCZ4z": "Expected Headcount Growth (next 12 months)",
        "opsQwCsEVnschNufM581ph": "Would you like Betafits to sign an NDA regarding your company and employee information?",
        "6eWgGjt7iTjtYcnZRfnCjm": "What is the full legal name of the company?",
        "4eLaFN3YpBRxS1gqEFhqG8": "State of formation",
        "aE23zBVWqLxxKfyZAacKm3": "Entity type",
        "6jRhRnuZ2kzaWXQEYjccAQ": "Will you be the signer for the NDA?",
        "52iYqLmZqi87WApC4ZUuM1": "NDA Signer's Title",
        "89C6yaJhUwD2hLhed5Pd9R": "NDA Signer's Name",
        "uJTQWkaMyr8daPGbwKfGJt": "NDA Signer's Email",
        "d4wVEowxCpRtdsXr81nFnF": "Which of the following benefits do you offer at this time?",
        "iHxYYn5HYHDvKGH7Ec9Z5L": "Renewal month of medical coverage",
        "gSmJUwa363oWH5x2Q68ojZ": "Desired effective date for quotes (if different than renewal)",
        "62Sic2EiCFMVuxwFUM9L1k": "How do you currently offer medical benefits?",
        "7XiD4e9FAysNviYb9ocJQd": "What is the medical contribution strategy?",
        "hRA1LaWSMrrX2irz3r6XXd": "Please describe your contribution strategy?",
        "aJ5QJvpDNyhXNMvoSmVEoT": "Contribution to Dependents (% or $)",
        "uaFGXRZwNyovwuXGKsCgDf": "Contribution to Employee (% or $)",
        "aByPiuEENQzRDaTFecMkKT": "Does the percentage apply only the base plan? Employees pay the full cost to buy up to other plans.",
        "b5zjBDR1YeKTq9GaVxQYWv": "Do you currently use a PEO?",
        "mM5ZyS9KeVz83eeqfdHoRn": "Which PEO do you use?",
        "vPgLS18szbAabJNGiwDnev": "What PEOs have you evaluated?",
        "kewbuyogJjkbbQNNXpbtxe": "Who is your payroll provider?",
        "i5Cg": "What is your Payroll Frequency?",
        "eKX8": "What is your Benefit Deduction Frequency?",
        "1DzLVcVYD9X23eBWJguR2p": "Do any of the following apply to your company or benefits package?",
        "iUedSGbFvtuwGorGfJLmoU": "Please provide additional details for each selected option",
        "hkZ8KcqU7mWUPnJK3WBybe": "In your opinion, what is the ideal number of medical plan options you would like to offer?",
        "qjLXquRvoppwrWfFrFNEnf": "Which of the following plan types do you think you would like to offer?",
        "p5mVMXPLaNV9YFDKZNT5Ri": "Total Cost (In choosing a carrier and plans, how important are the following?)",
        "uL9yj4Rhe57QLkjzEufduF": "Value for Money (In choosing a carrier and plans, how important are the following?)",
        "csQPgeHyH4ZAuCF4f7h8zR": "Carrier Name/Market Share (In choosing a carrier and plans, how important are the following?)",
        "eXnR1VZdpgJmCGCR3YgWWs": "Size of Network (In choosing a carrier and plans, how important are the following?)",
        "vfwAxLwvZ6VrLCp9uWz5wU": "Healthcare Navigation (In choosing a carrier and plans, how important are the following?)",
        "ptwJD4iPVBvA92FSgMPaA9": "Mental Health Resources (In choosing a carrier and plans, how important are the following?)",
        "8bKqEjRKcZQMEAYZWGNwjZ": "Telemedicine Access (In choosing a carrier and plans, how important are the following?)",
        "qAYFpWoy3ZHXcP968p3uh5": "Modern Technology and Support (In choosing a carrier and plans, how important are the following?)",
        "qLpBxT2RxYU81MgD6Qb48P": "Which of the following are notable benefits pain points for your company?",
        "pmcR22jTVUgcBSXBKQGMJq": "Which best describes your openness toward employees submitting individual health questionnaires as a part of the quoting process?",
        "awX85gzf6ywgCQsnu1HAKr": "Would you like to gather employee feedback for benchmarking and improving your benefits program?",
        "5gwf": "To upload a document, click the + Upload button below.",
        "8xGZP1oCmeWgPa2GhFquPc": "Benefits I.Y.O.W. (In Your Own Words)",
        "tP2QxuesGXQswTM8r8LNeV": "Is there anything else you would like us to know about your benefits package?",
    },
    "urHF8xDu7eus": {
        "iuLc": "What type of broker, platform, or consultant supports your employee benefits?",
        "q7SL": "Do you have a signed service agreement or only a Broker of Record (BOR) letter?",
        "1BQA": "Do you pay your broker any fees beyond commissions or standard premiums?",
        "kFtK": "Does your broker currently pay for or subsidize any of the following services?",
        "ucXn": "How often do you contact your broker for support?",
        "oXHq": "How often do you have strategic or renewal meetings with your broker?",
        "17Hj": "Which of the following services does your broker currently provide?",
        "4vRz": "How would you rate your broker’sresponsiveness and communication?",
        "9Xgb": "How would you rate your broker’srenewal strategy and plan benchmarking?",
        "mDVP": "How would you rate your broker’scompliance and documentation support?",
        "6aHN": "How would you rate your broker’sadmin coordination and day-to-day support?",
        "1YiE": "How would you rate your broker’svalue as a strategic partner?",
        "aJXW": "Please upload any broker documentation you have (e.g., signed service agreement or CAA compensation disclosure).",
    },
    "6eUGSndhtYus": {
        "4a93NzjYMKMaGEo9veT8pV": "Non-Disclosure Agreement (NDA) (Optional)",
        "akhj": "Record ID",
        "o19dKvYC9qGMfLEExpoXxf": "What is the company's full legal name?",
        "fmJquAsRkqBxEpnwyZwd4L": "What is the entity's state of formation?",
        "wk639YhY1EEpuZgidtntGq": "What is the entity type?",
        "gAQ1ThdizsjffXvXeL1Yxv": "Will you be the signer for the NDA?",
        "aCC2cW2taXLxHpXPsYYYgm": "Name of the NDA Signer",
        "teMNcdpmdLWx1psKKqHPV2": "Title of the NDA Signer",
        "7LD9hA4LaXHZqNYkJ64Gqg": "Email of the NDA Signer",
        "gQJ57d5ZjWPfej6teQoUuR": "What is the Legal Name of the Entity?",
        "qRv5QPb1PJ2EZ7QYMx5c6A": "Entity Type (Corporation, LLC, etc.)",
        "4DekuksCczyoSV6gDQ3ATv": "What is the Entity State of Formation?",
        "ccywgV1PQBZqeF8q5VxCkn": "Employer Identification Number",
        "qXwNuDfp6PMfG1GZfAuTmV": "Expected Benefit Start Month or Renewal of Medical Coverage",
    },
};

export const GROUP_DATA_FALLBACK_FIELD = "Additional Notes (Optional)";
